### ISSUE TITLE
Understanding the order of rules

### ISSUE THREAD

**Issue by LamerDrv** [henrypp/simplewall#1048]
Hi. Please help me to understand the logic of rule ordering in simplewall. I used other firewall and order of rules is significant in that other firewall.
For example, I want to solve this task:
1) allow access to local subnet 192.168.10.0/24 for all apps, but excluding 192.168.10.221 address.
2) allow access to 192.168.10.221 for Mozilla Firefox only (and disable access to this address for other apps)

In other product I would create several rules in correct order for solve this task:
1) allow rule: Mozilla Firefox to 192.168.10.221
2) block rule: any app to 192.168.10.221
3) allow rule: any app to 192.168.10.0/24
And here order of rules is important.

In simplewall I can't set the order of rules explicitly. How to solve this task in simplewall?

**Comment by rkmfl** [comment]
@LamerDrv - To clarify @roadarsi's comments:

To understand Simplewall, you have to think slightly different.  **In the default configuration, all traffic is blocked**.

In this standard configuration, any rules you create will **enable traffic to pass through**.  Therefore, no rules can be conflicting and rule-order does not matter because all rules are **reversing the default block/deny traffic rule**.

There is a section labeled "User Rules" where you can setup Allow/Block rules and this may lead to some confusion because using these "User Rules" you might assume a workflow as you mentioned in your post.

However, the "order" of the rules still is irrelevant because any blocking rule will ultimately override any allowing rule.

I your case, you wrote:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
1. allow rule: Mozilla Firefox to 192.168.10.221
2. block rule: any app to 192.168.10.221
3. allow rule: any app to 192.168.10.0/24
    And here order of rules is important.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

The #2 rule **blocks** the IP address 192.168.10.221

Therefore, regardless of any rules that allow traffic, the 192.168.10.221 rule, which blocks traffic, will prevail.

If you had 10 rules allowing traffic, in any order, but one rule blocking that traffic -- that traffic would still be blocked.

I hope that helps clarify :)

**Comment by LamerDrv** [comment]
Thanks you, roadarsi and rkmfl.
Now, it works.

PS: I look at https://docs.microsoft.com/en-us/windows/win32/fwp/filter-arbitration and I see that WFP logic is different from usual in other firewall products. Now I will have to learn the WFP logic :).
