### ISSUE TITLE
[BUG] Enable/disable Firewall checkbox is not remembered

### ISSUE THREAD

**Issue by Powsey** [henrypp/simplewall#1096]
Hello, I am not sure if this is a bug or a suggestion. 
I thought I was able to do that in former versions of the app so I'm gonna go with bug. 

<br />

### 1) Configuration
- OS : Windows 11 - Version 10.0.22000 Build 22000
- Simplewall: 3.6.1

<br />

### 2) Scenario
- Open simplewall
- Click on "Enable filters"
- Uncheck "Disable Windows Firewall"
- Click on "Enable filters"
>> Filters are enabled now
- Click on "Disable Filters"
- Uncheck "Enable Windows Firewall"
- Click again on "Disable Filters"
- Repeat from the beginning to observe the state of checkboxes "Disable Windows Firewall" / "Enable Windows Firewall" 

<br />

### 3) Expected behavior
Both checkboxes on the second attempt are unchecked. The state of the checkbox is remembered for next attemps. 
So when you uncheck one, it will stay unchecked until you check it. Same for checking them. 

<br />

### 4) Observed behavior
Both checkboxes are back to being checked by default. In order to not disable the firewall everytime for instance, you need to uncheck everytime before enabling filters. 

<br />

For my usage, it's a bit of a hassle. I'm using simplewall to limit my data usage (playing on a 4G mobile data plan). So I enable/disable filters quite often while playing/not playing. But I don't want my windows firewall to be changed everytime. I want to leave it as it is. 

Thanks for your feedback. 

Have a great day. 
Powsey

**Comment by henrypp** [comment]
This is not bug:

- Disable WF is [still recommended](1022) when SW is enabled.
- Enable WF is still recommended when SW is disabled.

**Comment by Powsey** [comment]
Alright, then I guess we can close this ticket.

**Comment by hegyre** [comment]
Hello,
I'm also in the case where I would like to keep WF enabled when using simplewall, just because I use it on a corporate laptop and I don't want corporate agents/scanners to detect I have disabled WF for any reason.
As such, I always enable temporary rules and uncheck the WF box.
Maybe we could have an option to set the defaults somewhere ? or the remember setting as in the ticket description ?

More than that, we could even thing of having an option to not show at all the dialog box at all when settings are saved maybe.
Just my 2 cents.

Cheers
