### ISSUE TITLE
Disable WFwAS on W10 Breaks Windows Apps Updates

### ISSUE THREAD

**Issue by HJLBX** [henrypp/simplewall#11]
Windows 10

Disable Windows Firewall breaks updates of Windows Apps

**Comment by henrypp** [comment]
win 10 build 14942 (and higher) killed svchost.exe, and Wfp Tool uses svchost.exe to allow windows update, so need to look into log (wfptool.log) i do not know what is blocked.

**Comment by HJLBX** [comment]
Windows Update is not broken when WFwAS is disabled

Update of Windows Apps\wappx (formerly Metro App) are broken when WFwAS is disabled on Windows 10, Version 1607, OS Build 14393.447

**Comment by henrypp** [comment]
need log.

**Comment by duttyend** [comment]
It seems that this problem is solved in Windows 10 RS3 using simplewall 2.0.18 and the latest version of Windows Store (11708.1001.30.0) : it is possible to update Metro apps while Windows Defender Firewall is off (somehow, @henrypp found a way to disable the Windows firewall without disabling its service)
