### ISSUE TITLE
Leaking connections

### ISSUE THREAD

**Issue by avrutg** [henrypp/simplewall#1130]
Hello! I use windows 10 enterprise with tons of telemetry disabled and additionally simple wall with blockage of everything not explicitly allowed. Simplewall works 99% of the time, however the leakage still occurs. On my router I can see connections to login.live.com etc(only connections to microsoft servers are leaking). Furthermore, AdGuard(an ad blocking app) can also see these connections on the device itself and block them. What can I do to investigate this issue? It's kind of driving me mad. Yesterday Edge update service installed itself.

**Comment by avrutg** [comment]
[filters.log](https://github.com/henrypp/simplewall/files/7774811/filters.log)

this is a renamed xml file

**Comment by elandorr** [comment]
I assume the blacklists SW uses are outdated. IP based filters unfortunately lag. On top of that, some particularly abusive applications today run their own DNS or hardcode IPs to avoid host based blacklists.

There is a new German study that found out with certain settings you can get telemetry to 0 without any modding. I think mainly it's the telemetry=0 in gp. (which used to not actually mean zero years ago when they did their first study) You might want to look that up.

I just set up new systems with this and can't confirm it unfortunately. And the broken update just makes things worse, I'm forced to allow svchost because the workaround needs a workaround :)

Technology sucks.

**Comment by henrypp** [comment]
Dont allow svchosts.exe
