### ISSUE TITLE
Simplewall with OnionFruit

### ISSUE THREAD

**Issue by anwar-alsilwy** [henrypp/simplewall#1131]
Hi Mr.Henry++
Happy Christmas.
I installed OninFruit on my PC ( https://dragonfruit.network/onionfruit ) it's open source program that makes all applications connect through Tor network to unblock forbidden websites.
After run OnionFruit, it requested allow from simplewall and I gave it.
The problem is after OnionFruit connect successfully, all blocked applications on simplewall can reach to the internet and eat my internet balance even if the simplewall filters enabled !!!
You can test simplewall with OnionFruit by yourself to find the solution.
And please, is it possible to make simplewall compatible with OnionFruit.
Thanks for your hard work.

**Comment by jacob755** [comment]
im not sure if its work
uncheck allow loopback connection for all
if work the way you want then ok
but if not work try this
 in user rules tab right click  select add...
in general tab give it name (example:loop )
in rule tab add 127.0.0.1 in remote if its not work add local too (later)
don't enable rule and save it
now if any app which need loopback connection
right click on it and select apply loop for this app
report which way work

**Comment by anwar-alsilwy** [comment]
Ok thanks for let me know, I will test the solution soon ... wait for report !!!
Question please: If OnionFruit support "VPN Mode" on future release, You think simplewall can handle with it normally, not complicated like "Proxy mode" ?? Or it will bypass simplewall filters  too ??

**Comment by anwar-alsilwy** [comment]
Ok well ..
The first method works perfectly 100% ( uncheck allow loopback connection for all ), So Tor connections came only for allowed applications by simplewall.
That's Great !!!
But the second method is not, Tor connections simply bypass all filters of simplewall  ( I added 127.0.0.1 to Remote firstly, then to Local too without hope),
Anyway, thank you so much (Jacob755) for this magic solution, and thanks to (Henrypp) and all Contributors of this great project.

**Comment by gettysburg** [comment]
I recommend Whonix (https://www.whonix.org) instead of OnionFruit - it runs Debian inside two VirtualBox instances, and is much safer than Onionfruit.

Take a look if it fits your needs.

I am not affiliated with Whonix or the developers in any way.

**Comment by anwar-alsilwy** [comment]
> 

Serious consequences !!!!! more details please ?
And could you please explain how to create appropriate rules for loopback ?

**Comment by gettysburg** [comment]
Some applications (especially web-browsers) use the loop-back interface to communicate with child processes, one example:

![Capture](https://user-images.githubusercontent.com/2256003/147935341-3e800adf-b0c2-4ee2-8a74-c53c7c5314c4.JPG)

You would whitelist this behavior as you would with normal network traffic, by taking a look at the packet log, searching for valid programs getting blocked from creating sockets or connections on localhost / 127.0.0.1, and then creating a matching rule.

Whonix was just a suggestion because I have previous experience using it, but did you take a look at it, and does it fit your needs? Or, do you prefer your current setup, which seems to be working fine for you now?

**Comment by anwar-alsilwy** [comment]
Whonix is interesting, It's working via VM and it's creat actually 2 VMs, first for creat Tor connection, and 2nd for creat virtual gateway.
At the moment My pc is old enough to run all these VMs.
One thing please, when I go to (Packet Log) in simplewall it's empty all the time and not capturing any thing about blocked apps, what's the matter ???

**Comment by gettysburg** [comment]
What are your current settings of simplewall?

Block all incoming and outgoing traffic, but allow all loopback traffic? If so, then maybe your setup is just working as it should, I would interpret it as a good sign, you just might not have programs installed which send data over the loopback interface like Mozilla Firefox (other techniques exist for that, namely IPC short for Inter process-communication / pipes which don't rely on the TCP/IP stack at all).

4 gigabytes of RAM (for the VM's!) and at least a quad-core CPU with VT-x/AMD-V is all it takes to get Whonix running, so if your setup isn't from 2006, it will likely run.

Also about Whonix's concept, you got that slightly wrong:

One virtual machine (the gateway) is the machine with Tor installed on it, and it has two network interfaces, one to communicate with your local network and establish a connection to a Tor relay or Bridge, and one connected to a virtual router / network, so that the second virtual machine, namely your Workstation, which has only one network interface connected to the virtual network, where you do all your work, can access the gateway through firewall rules on both machines. Whonix runs in VirtualBox / VM software to protect you in case even a virus, malware or trojan gets on to your Whonix-Workstation.

Said malware would not be able to determine your location or IP address, and not be able to escape the security boundaries of the Virtual Machine. With the VM backup and restore feature, you could use this in many ways, i.e. to actively analyze malware, and when you are done, revert the Workstation back to a known, good (i.e. not-infected state) that you created before you began your work.

Hope I was able to help after a (very) tiring night of work.

**Comment by anwar-alsilwy** [comment]
Ok, thanks allot (gettysburg) for explaining.
But I need some help:
I unchecked (allow loopback connection for all ),
I want i.e. to let Firefox only to connect through loopback,
How to create rule in correct way, and where should I put 127.0.0.1, in Remote or Local address ??

**Comment by gettysburg** [comment]
Hi,

in Rule Editor: You would select TCP as the protocol, set direction to Any, and then put the address of the loopback interface in the remote field, and only apply the rule to the Firefox binary.

If you want to be super paranoid about it, you can also put the loopback-address in both the local and remote fields.

**Comment by anwar-alsilwy** [comment]
Ok, works great, thanks
But what will happen if I choose protocol to any
and direction to any, is it bad config ??
