### ISSUE TITLE
SIMPLEWALL IS FAILING WHEN UPDATING ITSELF

### ISSUE THREAD

**Issue by AVM-Ven** [henrypp/simplewall#1148]
First, a message appears:  Update available. Do you want to download it?  You reply yes, it downloads a few data. Then, it asks to install it. But your reply (a click on the OK button) is never accepted. The dialog hangs and never gets to move.  CAN YOU PLEASE FIX THIS?

**Comment by Powsey** [comment]
Hello AVM-Ven, a bug with the update installation occured in the past (normally at version 3.5.3).

This bug was fixed in version 3.6. However, since the bug concerns the updater, you need to install manually the update to fix this. Otherwise you will stay stuck in the bugged version. Future updates should flow normally after that.

You can download the latest version from here: https://github.com/henrypp/simplewall/releases/tag/v.3.6.1

In addition, I would like to remind you that this is a free software made with lots of love and a supporting community. Therefore, screaming with capital letters in both your title and description has nothing to do here.

So for your future tickets, take the time to explain in details what exactly is happening to you (machine, OS, simplewall versions, screenshots, etc.) and do this respectfully please.
Thank you

**Comment by henrypp** [comment]
> So for your future tickets, take the time to explain in details what exactly is happening to you (machine, OS, simplewall version, screenshots, etc.) and do this respectfully please. Be kind.

for future just search for duplicates #1061

**Comment by unkn000wn** [comment]
First, a message appears: Update available. Do you want to download it? You reply yes, it downloads a few data. Then, it asks to install it. But your reply (a click on the OK button) is never accepted. The dialog hangs and never gets to move. CAN YOU PLEASE FIX THIS?
I have this problem too.
My version is 3.7.2 found update 3.7.3. ater window update popap after reboot windows i am click update? but program                      ot updated and still remains 3.7.2 version
i am trided install in manual mode previous version, and automatic update sleel remains not work.
Work only donwload and manual update. if need i can record screen video.
