### ISSUE TITLE
[Question] How to only allow port 53 for system?

### ISSUE THREAD

**Issue by Rexadev** [henrypp/simplewall#1174]
I want to block 53 for all except the system apps (it is taken care off by simplewall system rules) to prevent DNS bypass. But chrome doesn't work when port 53 is blocked.

1. Even DoH doesn't work with 53 blocked for svchost.exe
2.  Please fix it by changing the "system rule" for DNS @henrypp
3. Is dnscache not needed for it it in system rules
4. What else is svchost  used for, the rule to suggested will only allow it to access DNS. Is it not used for widows update?
5. > Could you elaborate on what you mean by "DNS bypass", and additionally tell me what operating system you are currently using?

You got it I meant apps can use there own DNS to bypass domain blocking

1. Blocking port 53 globally (no apps selected) and allowing 53 for svchost.exe doesn't work. something else also needs to be allowed.
2. Also if I only allow svchost.exe to access port 53 will it not stop it's other functions?

I only want the windows DNS component to access port 53 but only allowing svchost breaks internet so i applied a global rule but my dns specified

some other component other than svchost needs to be allowed to use port 53.
Anyways, I have allowed 443 and 80 as default/global rule and that is not the problem

**Comment by DomOBU** [comment]
The situation is the same with Firefox which has the same constraint.

**Comment by gettysburg** [comment]
Hi, on newer Windows systems, svchost.exe takes care of DNS resolving, no matter what programming interface your web browser tries to use to resolve domain names, these are my rules for it:

![one](https://user-images.githubusercontent.com/2256003/162412053-a6f204c5-de39-4923-a9fb-cea00bc95dd3.JPG)
![two](https://user-images.githubusercontent.com/2256003/162412062-9858c2bc-e548-442c-8696-bbd2be3697e4.JPG)
![three](https://user-images.githubusercontent.com/2256003/162412070-99f4a306-a392-41ef-8227-6e1410ab8454.JPG)

Even if this does not affect you, why would you want to give your system apps rights to resolve host names? Microsoft and Windows are not exactly known for their excellent track record when it comes to security and privacy, or fast response time on zero-day exploit exposure.

Could you elaborate on what you mean by "DNS bypass", and additionally tell me what operating system you are currently using?

@Rexadev 
@DomOBU

**Comment by Rexadev** [comment]
1. Even DoH doesn't work with 53 blocked for svchost.exe
2.  Please fix it by changing the "system rule" for DNS
3. Is dnscache not needed for it it in system rules
4. > Could you elaborate on what you mean by "DNS bypass", and additionally tell me what operating system you are currently using?
You got it I meant apps can use there own DNS to bypass domain blocking

@gettysburg

**Comment by gettysburg** [comment]
@Rexadev 

I don't think so, there are only a few API's to use the ethernet cables configured DNS servers, and as I mentioned already, on newer Windows systems, **svchost.exe** takes care of **all* DNS resolving, the various headers/libraries compiled into your program are merely proxies to the one process that does the actual resolving, Microsoft would probably claim that this improves the cache hit rate.

> Is dnscache not needed for it it in system rules

No, as either dnscache would connect to the resolver through the loopback interface or other ways of [Interprocess communications](https://docs.microsoft.com/en-us/windows/win32/ipc/interprocess-communications).

> What else is svchost used for?

All kinds of things, for example time synchronization - However, I get along just having two user rules configured for svchost - DNS and NTP - note that __all__ other rules from the "Services", "UWP Apps" and "System Rules" tabs are disabled. Generally it is advised to create a tight firewall configuration, the same thing you would aim for in access control systems.

> Even DoH doesn't work with 53 blocked for svchost.exe

If this really is the case, then simplewall is highly likely to be related to your set of problems. May I remind you, that upon simplewall activation, ### ALL network traffic is blocked until you have created a rule for __every single app that wants to use the internet__.

> You got it I meant apps can use there own DNS to bypass domain blocking

Then create a more strict config, unless this is wanted - sorry, but the language barrier is a bit of a problem to be honest.

**Comment by gettysburg** [comment]
@Rexadev 

I don't think so, there are only a few API's to use the ethernet cables configured DNS servers, and as I mentioned already, on newer Windows systems, **svchost.exe** takes care of **all* DNS resolving, the various headers/libraries compiled into your program are merely proxies to the one process that does the actual resolving, Microsoft would probably claim that this improves the cache hit rate.

> Is dnscache not needed for it it in system rules

No, as either dnscache would connect to the resolver through the loopback interface or other ways of [Interprocess communications](https://docs.microsoft.com/en-us/windows/win32/ipc/interprocess-communications).

> What else is svchost used for?

All kinds of things, the two ones using the internet are DNS and time synchronization using NTP - However, I get along just having two user rules configured for svchost - DNS and NTP - note that __all__ other rules from the "Services", "UWP Apps" and "System Rules" tabs are disabled. The tighter the firewall rules, the better, so instead of allowing one port for the entire system and all users and programs on it, make your rule app, protocol, family, direction, IP address and port specific, as far as that is possible.

> Even DoH doesn't work with 53 blocked for svchost.exe

If this really is the case, then simplewall is highly likely to be related to your set of problems. May I remind you, that upon simplewall activation, __All network traffic is blocked until you have created a user rule for every single app that wants to use the internet__.

> You got it I meant apps can use there own DNS to bypass domain blocking

Then create a more strict config, unless this is wanted - sorry, but the language barrier is a bit of a problem to be honest.

**Comment by gettysburg** [comment]
@Rexadev 

> You got it I meant apps can use there own DNS to bypass domain blocking

That's possible but rare, there are only a few API's to use the ethernet connections DNS servers, and as I mentioned already, on newer Windows systems, **svchost.exe** takes care of **all* DNS resolving, the various headers/libraries compiled into your program have been changed and are now merely proxies to the one process that does the actual resolving - sure, there are apps that have written their own low-level DNS resolving code, or use such libraries, but they are rather rare.

> Is dnscache not needed for it it in system rules?

The service named dnscache misleadingly called "DNS Client", does not do any resolving on it's own. Here's an excerpt from it's service documentation:

```The DNS Client service (dnscache) caches Domain Name System (DNS) names, and registers the full computer name for this computer.  If the service is stopped, DNS names will continue to be resolved.  However, the results of DNS name queries will not be cached and the computer's name will not be registered.```

So no, it is not needed - refer to my paragraph below, you don't need **ANY** of the rules from the "Services", "UWP Apps" and "System Rules" tabs, they are convenient fast-fixes only.

> What else is svchost used for?

All kinds of things, the two features that I've discovered to be using the internet so far are DNS and time synchronization using NTP - So,I get along with just having two user rules configured for svchost - note that __all__ other rules from the "Services", "UWP Apps" and "System Rules" tabs are disabled. The tighter the firewall rules, the better, so instead of allowing one port for the entire system, all users and programs on it, make your rule app, protocol, family, direction, IP address and port specific, as far as that is possible.

> Even DoH doesn't work with 53 blocked for svchost.exe

This does not make any sense, DNS-over-HTTPS uses port 443 and is implemented into your browser.

simplewall is highly unlikely to be your cause of problems. May I remind you, that upon simplewall activation, __All network traffic is blocked until you have created a user rule for **every single app that wants to use the internet?**

I hope I could somehow you.

**Comment by DomOBU** [comment]
@Rexadev
@gettysburg 
On my daily pc I use a different FW than simplewall.
On this one, if I block the access of svchost.exe to ports 80 & 443 Windows Update does not work.
If I allow the ports again Windows Update works again.

**Comment by Rexadev** [comment]
@gettysburg 

1. Blocking port 53 globally (no apps selected) and allowing 53 for svchost.exe doesn't work. something else also needs to be allowed.
2. Also if I only allow svchost.exe to access port 53 will it not stop it's other functions?

**Comment by gettysburg** [comment]
>If I allow the ports again Windows Update works again.

Yes, sorry I forgot to mention that svchost also facilitates downloading of Windows Updates, I partially forgot to mention it because the way I handle it is the following: I open the "Search for Updates" window - fun fact, that alone, on my system, makes systemsettings.exe and svchost.exe try to connect to the internet 5 times:

![image](https://user-images.githubusercontent.com/2256003/162803159-738f25ad-5205-4929-8d75-062bcbb16fb3.JPG)

So after it did that, I disable all filters, search for updates, if none are found, I re-enable the filters, if updates are found, I let it download the updates, and re-enable them the second all updates are downloaded,

> Blocking port 53 globally (no apps selected) and allowing 53 for svchost.exe doesn't work. something else also needs to be allowed.

Can you please, again, try to explain, in great detail, what kind of "DNS Bypass" you fear? Generally, you should allow **as little as possible** internet access to your applications, so if on your system, svchost.exe does not resolve DNS queries like it does on my system, then you don't even need to create a rule to block port 53 for it - assuming "Block all outgoing network connections is enabled" - from there on, you create a rule-set for all applications requiring internet access. 

I use simplewall with the "Block inbound connections for all" and "Block outbound connections for all" options enabled, and you should do the same.

**Comment by gettysburg** [comment]
>If I allow the ports again Windows Update works again.

Yes, sorry I forgot to mention that svchost also facilitates downloading of Windows Updates, I partially forgot to mention it because the way I handle it is the following: I open the "Search for Updates" window - fun fact, that alone, on my system, makes systemsettings.exe and svchost.exe try to connect to the internet 5 times:

![image](https://user-images.githubusercontent.com/2256003/162803159-738f25ad-5205-4929-8d75-062bcbb16fb3.JPG)

So after it did that, I disable all filters, search for updates, if none are found, I re-enable the filters, if updates are found, I let it download the updates, and re-enable them the second all updates are downloaded,

> Blocking port 53 globally (no apps selected) and allowing 53 for svchost.exe doesn't work. something else also needs to be allowed.

Can you please, again, try to explain, in great detail, what kind of "DNS Bypass" you fear? Generally, you should allow **as little as possible** internet access to your applications, so if on your system, svchost.exe does not resolve DNS queries like it does on my system, then you don't even need to create a rule to block port 53 for it - assuming "Block all outgoing network connections is enabled" - from there on, you create a rule-set for all applications requiring internet access. 

I use simplewall with the "Block inbound connections for all" and "Block outbound connections for all" options enabled, and you should do the same - if you do, you should get a notification for each new app trying to access the internet.

If by DNS bypass you mean a DNS leak, then no, if simplewall and your VPN is correctly configured, all traffic will go through the DNS tunnel, including DNS requests, which will be resolved using the VPN server's configured DNS servers.

**Comment by gettysburg** [comment]
Yes, of course it breaks internet, you also need to add two rules for your Web Browser, namely for Port 443 TCP and UDP, don't bother whitelisting TCP Port 80 / visiting sites that haven't upgraded to HTTPS even though free certificates have been available for years now.

You can also send me your settings file as an e-mail attachment to the address listed on my profile. To export your settings file, go to File -> Export.

**Comment by gettysburg** [comment]
I can not help you until I have seen your configuration, if you do not want to share that, I can only offer you to start over and explain to me what the hell you are trying to do here and why, I am not always on the same computer, in the meantime I am also helping clients in real life et cetera. My memory is also not the best and I'm not willing to read entire tickets / threads full of text again and again.

If you want fast and accurate answers, please learn how to post accurate information about your problem and system, and ideally attach / send me your configuration file - I'm not angry, but I just arrived at home and it frustrates me too when I'm unable to help someone. Oh well..

@DomOBU Can you please decipher what his exact problem is? You seem to understand the first post, I don't - of course web browsers don't work if you block DNS, or disable the system DNS rule. However, if you then make a user rule, for, depending on your system version, your systems DNS resolver, then it will work again. 

It's just that with the newer versions of Windows, svchost takes care of ALL DNS resolving except for programs who have compiled in a library to do it on their own (very rare, only MegaSync does this on my PC and I have quite a lot of programs installed). I did not need to add a DNS user rule for Firefox yet it works fine. My firefox version is 91.8.0esr (64-bit).

So, without further information, I'm out. I tried..
