### ISSUE TITLE
I need a version with vietnamese

### ISSUE THREAD

**Issue by binhnguyen99391** [henrypp/simplewall#1179]
I know it's annoying but can you provide the Vietnamese version for the next updated version?
I'd be happy to provide a translation so you can insert the code into the program
Looking forward to your feedback

**Comment by Powsey** [comment]
Hello, then you can provide the translation. 

Here is how to proceed:
- the original lang file is here : https://github.com/henrypp/simplewall/blob/master/bin/i18n/!example.txt
- create an INI file like this one (this is a French example) : https://github.com/henrypp/simplewall/blob/master/bin/i18n/French.ini
- add your INI file in this folder: https://github.com/henrypp/simplewall/tree/master/bin/i18n

From there you'll be able to send a pull request so that your new file is added to the mix.
Thank you
