### ISSUE TITLE
Simplewall exists by itself

### ISSUE THREAD

**Issue by ido1990** [henrypp/simplewall#1185]
Hi!
My PC is running Windows 10 upgraded from Windows 7, since the upgrade I saw Simplewall exits by itself without me touching.
I'm not sure why but it's the second time I see this happening...
The close dialog is popping for a brief second and then the Simplewall icon disappears.

How can I find the cause?
I did a virus scan but found nothing.
Thanks in advance!

**Comment by gettysburg** [comment]
Did you start the update from within Windows 7, sometimes called Anytime Upgrade? This copies all your files and programs,

**Comment by gettysburg** [comment]
Did you start the update from within Windows 7, sometimes called Anytime Upgrade? This copies all your files and programs.

**Comment by gettysburg** [comment]
Did you start the update from within Windows 7, by using Anytime Upgrade or the downloadable Windows 10 Installer? This copies all your files and programs.

If you used an ISO file and copied it to a flash drive, it might also offer you to keep your files and programs.

If you want to be sure that the file has not been modified, compare the checksums with the versions available on GitHub. As for the quitting, I can't explain that, but simply re-installing the program should work, maybe the Windows 10 installer got rid of the old registry, I never used the "keep your files & programs" option so I don't know how it actually behaves.

Hope this helps.

**Comment by ido1990** [comment]
I started the update from within Windows 7 with the Windows 10 installer and indeed I had all my files and programs.
Had some updates for simplewall since then so I thought it might be OK.
Just reinstalled, let's see if it's gone.

**Comment by gettysburg** [comment]
It should be, otherwise follow the instructions I have posted in #1188 to check if it is crashing and provide us with the application fault information from event viewer so I can debug this issue.

Good luck, hope it works fine now!

**Comment by ido1990** [comment]
So it happened again (I saw the simplewall icon and when I wanted to click on it, it dissapeared).
I tried looking on the Event Viewer but I couldn't find anything mentioning simplewall.
Do you have any idea why?

**Comment by gettysburg** [comment]
No application crash logged under Windows Logs -> Application when you open Event Viewer? There might be hundreds if not thousands of entries so it could be easy to miss.

If it's not crashing then either the app is silently terminating itself (don't know why it would), or some other program on your PC is ending the process in a clean manner, explaining why there is no application crash event. This could be Anti-Virus / Anti-Exploit software, malware or programs claiming to improve system or video-game performance.

Try upgrading to v.3.6.2, which got released yesterday - if the issue persists, this is likely an **isolated** issue with your system, and I would advise you to backup your most important documents (but no executable files which could re-infect your system), then download a clean install medium (verify the hash of any ISO file you download), and completely format your hard-drive by overwriting it with zeros (Linux install media is great for this task, particularly non-bloated distributions like ArchLinux) -  you can write most Linux install media to a USB thumb-drive using [Win32DiskImager](https://sourceforge.net/projects/win32diskimager), then boot them and use a tool such as dd as described [here](https://wiki.archlinux.org/title/Securely_wipe_disk). If you have other hard-drives, make backups as well, and format them as well. Once every disk has been formatted, re-install your OS on your main disk.

The above paragraph only applies if you also suspect that you are a victim of viruses or malware, you can try downloading a 30-day trial version of Kaspersky and Malwarebytes, and run a full scan with each tool to see if anything has been found - if that's the case, you should completely wipe your disks, because no human-made anti-virus solution has a 100% detection rate, and you don't know what might be left on your system, undetected.

If you have any SSD / NVME drives, performing an [ATA Secure Erase](https://ata.wiki.kernel.org/index.php/ATA_Secure_Erase) will also get you your initial drive read / write performance back. It can also be done using Linux Install Media, but for optimal drive and controller support, I would download a distribution that has a very modern kernel and version of hdparm pre-installed, such as ArchLinux.

If you want to figure out why simplewall actually quits, you would have to attach a debugger, such as [x64dbg](https://x64dbg.com) and wait for simplewall to quit, but from the delay between our messages, it seems like this could take easily take 3 weeks, and if you are not familiar with x64dbg, you might also not be able to give us the data we need. Re-installing would be much quicker and would also guarantee a virus-free system (again, the whole virus thing is just a possibility).

Hope I could help, somehow. 👍

**Comment by gettysburg** [comment]
No application crash logged under Windows Logs -> Application when you open Event Viewer? There might be hundreds if not thousands of entries so it could be easy to miss.

If it's not crashing then either the app is silently terminating itself (don't know why it would), or some other program on your PC is ending the process in a clean manner, explaining why there is no application crash event. This could be Anti-Virus / Anti-Exploit software, malware or programs claiming to improve system or video-game performance.

Try upgrading to v.3.6.2, which got released yesterday - if the issue persists, this is likely an **isolated** issue with your system, and I would advise you to backup your most important documents (but no executable files which could re-infect your system), then download a clean install medium (verify the hash of any ISO file you download), and completely format your hard-drive by overwriting it with zeros (Linux install media is great for this task, particularly non-bloated distributions like ArchLinux) -  you can write most Linux install media to a USB thumb-drive using [Win32DiskImager](https://sourceforge.net/projects/win32diskimager), then boot them and use a tool such as dd as described [here](https://wiki.archlinux.org/title/Securely_wipe_disk). If you have other hard-drives, make backups, and format them as well. Once every disk has been formatted, re-install your OS on your main disk.

The above paragraph only applies if you also suspect that you are a victim of viruses or malware, you can try downloading a 30-day trial version of Kaspersky and Malwarebytes, and run a full scan with each tool to see if anything has been found - if that's the case, you should completely wipe your disks, because no human-made anti-virus solution has a 100% detection rate, and you don't know what might be left on your system, undetected.

If you have any SSD / NVME drives, performing an [ATA Secure Erase](https://ata.wiki.kernel.org/index.php/ATA_Secure_Erase) will also get you your initial drive read / write performance back. It can also be done using Linux Install Media, but for optimal drive and controller support, I would download a distribution that has a very modern kernel and version of hdparm pre-installed, such as ArchLinux.

If you want to figure out why simplewall actually quits, you would have to attach a debugger, such as [x64dbg](https://x64dbg.com) and wait for simplewall to quit, but from the delay between our messages, it seems like this could take easily take 3 weeks, and if you are not familiar with x64dbg, you might also not be able to give us the data we need. Re-installing would be much quicker and would also guarantee a virus-free system (again, the whole virus thing is just a possibility).

Hope I could help, somehow. 👍

**Comment by gettysburg** [comment]
No application crash logged under Windows Logs -> Application when you open Event Viewer? There might be hundreds if not thousands of entries so it could be easy to miss.

If it's not crashing then either the app is silently terminating itself (don't know why it would), or some other program on your PC is ending the process in a clean manner, explaining why there is no application crash event. This could be Anti-Virus / Anti-Exploit software, malware or programs claiming to improve system or video-game performance.

Try upgrading to v.3.6.2, which got released yesterday - if the issue persists, this is likely an **isolated** issue with your system, and I would advise you to backup your most important documents (but no executable files which could re-infect your system), then download a clean install medium (verify the hash of any ISO file you download), and completely format your hard-drive by overwriting it with zeros (Linux install media is great for this task, particularly non-bloated distributions like ArchLinux) -  you can write most Linux install media to a USB thumb-drive using [Win32DiskImager](https://sourceforge.net/projects/win32diskimager), then boot them and use a tool such as dd as described [here](https://wiki.archlinux.org/title/Securely_wipe_disk). If you have other hard-drives, make backups as well, and format them as well. Once every disk has been formatted, re-install your OS on your main disk.

The above paragraph only applies if you also suspect that you are a victim of viruses or malware, you can try downloading a 30-day trial version of Kaspersky and Malwarebytes, and run a full scan with each tool to see if anything has been found - if that's the case, you should completely wipe your disks, because no human-made anti-virus solution has a 100% detection rate, and you don't know what might be left on your system, undetected.

If you have any SSD / NVME drives, performing an [ATA Secure Erase](https://ata.wiki.kernel.org/index.php/ATA_Secure_Erase) will also get you your initial drive read / write performance back. It can also be done using Linux Install Media, but for optimal drive and controller support, I would download a distribution which has a very modern kernel and version of hdparm pre-installed, such as ArchLinux.

If you want to figure out why simplewall actually quits, you would have to attach a debugger, such as [x64dbg](https://x64dbg.com) and wait for simplewall to quit, but from the delay between our messages, it seems like this could take easily take 3 weeks, and if you are not familiar with x64dbg, you might also not be able to give us the data we need. Re-installing would be much quicker and would also guarantee a virus-free system (again, the whole virus thing is just a possibility).

Hope I could help, somehow. 👍

**Comment by henrypp** [comment]
Maybe simplewall crashed, but you disabled crash dumps entirely, thats why you did not see anything.

**Comment by ido1990** [comment]
The problem has happened to me several more times since then but it's not consistent and everything I tried in order to debug it, failed.
BTW, it didn't crash, I could see the program opens, the small quit message pops up and the Yes button pressed but it happened very quickly and I had control on my cursor all this time.
Doesn't seem like a crash to me.

**Comment by henrypp** [comment]
Try enable "Snow confirmation on exit". Maybe some shit headed applications sends WM_CLOSE to SW, idk!

**Comment by ido1990** [comment]
![תמונה](https://user-images.githubusercontent.com/16368652/191493366-47296c46-af45-41f6-801b-c646f5a8fe25.png)

Where can I find it?

**Comment by henrypp** [comment]
settings, interface

**Comment by ido1990** [comment]
Already checked.
I guess it will stay a mystery...
![תמונה](https://user-images.githubusercontent.com/16368652/191494880-28da4621-0399-4bd6-9130-7fcac322e353.png)
