### ISSUE TITLE
outlook rules

### ISSUE THREAD

**Issue by TechGabor** [henrypp/simplewall#1186]
Hi!

I want to set-up:
outlook work 
enable only: 94.xx.xx.xx:993 ... 
drop: all other site.
[https://tinypic.host/i/outlook2.6Ep6d](url)
[https://tinypic.host/i/outlook3.6Ewsq](url)

After setup outlook work with all ip. 

[https://tinypic.host/i/outlook1.6Ebqg](url)

**Comment by gettysburg** [comment]
Hi TechGabor, are you sure that "Block all outgoing network connections" is enabled?

It doesn't look like it, since you only have one app / rule configured (the rule for Outlook), if said option was enabled you would have to create rules for all programs that need internet access, which at the bare minimum would be:

svchost.exe which handles all DNS resolving (at least on Windows Server 2019) and clock synchronization.
Your web browser (Port 443 on TCP and UDP).

Please check your configuration, this is highly unlikely to be a problem with simplewall.
