### ISSUE TITLE
Autoload from windows

### ISSUE THREAD

**Issue by AxelHirsch** [henrypp/simplewall#1188]
Hey Henry. You have a good firewall. But there is one problem. When the system starts, it loads and if the application tries to go online, it asks what to do. But after a couple of days it is no longer visible in the tray and all new connections are automatically blocked. You have to start it manually. Of course, I set it to autorun windows and in the program settings it is also worth booting with the system. How to solve this problem?

**Comment by gettysburg** [comment]
You mean after leaving the computer on for a couple of days, without rebooting?

It shouldn't automatically quit / crash like that - for example, my Workstation has been running for up to 39 days and it hasn't disappeared for me yet, even after locking / leaving it alone for longer periods of time :-)

What Windows version are you using, and do you run any antivirus software? Is hibernation / sleep enabled?

This could also be the (_unlikely_) sign of a system infection, some malware automatically terminates a broad range of user mode firewalls, the rules however still apply because the actual filtering happens in kernel mode.

You could try looking for application faults using the Windows Event Viewer, to see if _simplewall.exe_ crashes (open Event Viewer as Administrator, then navigate to Windows Logs -> Application, and then look for entries with the level "Error").

An example entry looks like this:

```
Faulting application name: kleopatra.exe, version: 3.1.20.0, time stamp: 0x00000000
Faulting module name: libKF5ConfigWidgets.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0002cce0
```

If you indeed find such an entry for simplewall, then copy the 4 fields above from your event viewer, and also supply your simplewall version.

Thank you.

**Comment by gettysburg** [comment]
You mean after leaving the computer on for a couple of days, without rebooting?

It shouldn't automatically quit / crash like that - for example, my Workstation has been running for up to 39 days and it hasn't disappeared for me yet, even after locking / leaving it alone for longer periods of time :-)

What Windows version are you using, and do you run any antivirus software? Is hibernation / sleep enabled?

This could also be the (_unlikely_) sign of a system infection, some malware automatically terminates a broad range of user mode firewalls, the rules however still apply because the actual filtering happens in kernel mode.

You could try looking for application faults using the Windows Event Viewer, to see if _simplewall.exe_ crashes (open Event Viewer as Administrator, then navigate to Windows Logs -> Application, and then look for entries with the severity level "Error").

An example entry looks like this:

```
Faulting application name: kleopatra.exe, version: 3.1.20.0, time stamp: 0x00000000
Faulting module name: libKF5ConfigWidgets.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0002cce0
```

If you indeed find such an entry for simplewall, then copy the 4 fields above from your event viewer.

Thank you.

**Comment by gettysburg** [comment]
You mean after leaving the computer on for a couple of days, without rebooting?

It shouldn't automatically quit / crash like that - for example, my Workstation has been running for up to 39 days and it hasn't disappeared for me yet, even after locking / leaving it alone for longer periods of time :-)

What Windows version are you using, and do you run any antivirus software? Is hibernation / sleep enabled?

This could also be the (unlikely) sign of a system infection, some malware automatically terminates a broad range of user mode firewalls, the rules however still apply because the actual filtering happens in kernel mode.

You could try looking for application faults using the Windows Event Viewer, to see if simplewall.exe crashes (open Event Viewer as Administrator, then navigate to Windows Logs -> Application, and then look for entries with the severity level "Error").

An example entry looks like this:

Faulting application name: kleopatra.exe, version: 3.1.20.0, time stamp: 0x00000000
Faulting module name: libKF5ConfigWidgets.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0002cce0

If you indeed find such an entry for simplewall, then copy the 4 fields above from your event viewer and put them in your reply.

Thank you.

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1141#issuecomment-1044264827
