### ISSUE TITLE
"User Rule" for a Program doesn't bypass Global system rules.

### ISSUE THREAD

**Issue by Rexadev** [henrypp/simplewall#1191]
I tried creating a allow rule with any protocol/IPv/In-Out with NoRules and adding programs to that rule. MAYBE that doesn't work because for ProtonVPN, Call Of Duty (Battle.net Launcher) to work I have to disable whole simplewall.

It is all green but using tinywall's "Show Connection" It says somethings are blocked it is not blocked from simplewall or tinywall but VPN worked when simplewall is disabled

**Creating rule on per app basis is useless. that means simplewall is for blocking not for allowing. allow rule will be usefull if custom order was available. Example to only allow certain ports. 
_I would really like Per-App only setting(not rulesets with some apps selected) with custom order of allow and block rules._
 @henrypp**

**Comment by gettysburg** [comment]
Okay, here is how I did it when I used OpenVPN (and most VPN's are OpenVPN based):

Apps:

Only allow the OpenVPN binary and your VPN server remote IP address, port and protocol, for outbound connections.

If you have "Allow loopback connections" enabled, which is recommended, OpenVPN should do it's magic and forward any packets sent through your public ethernet interface through it's established tunnel. This works because OpenVPN temporarily changes your IPv4 network settings (specifically, the gateway one), in order to capture packets (at least that's what the logs on low verbosity told me).

Make sure that OpenVPN is running under an Administrator account, otherwise it might lack permissions to do the necessary changes.

If you are still having problems, I suggest you to download OpenVPN on it's own, not through a third-party launcher, and get a respective config file from ProtonVPN - this way you will be able to see the OpenVPN log and debugging is much easier - it even has a small GUI in your tray.

But yeah, one rule (the one to my OpenVPN server) was all it took, even with a strict firewall - maybe I am forgetting something here, it's been a while since I used OpenVPN.

**Comment by Rexadev** [comment]
Creating a rule for only protonVPN exe s doesn't do anything It is still blocking it somehow the userrules with no apps selected should only apply to app without any user rules specified but it is acting as a global rule

**Comment by gettysburg** [comment]
> The user rules with no apps selected should only apply to app without any user rules specified but it is acting as a global rule.

If no app is selected, the rule will act globally - this is wanted behavior.

Have you tried using the logger to resolve this?

Usually VPN services are rather easy to setup.

**Comment by Rexadev** [comment]
But when apps are selected only those rules are applied? So when no apps are selected is not global but applied to those with a rule specified?

**Comment by Rexadev** [comment]
> Have you tried using the logger to resolve this?

It is all green but using tinywall's "Show Connection" It says somethings are blocked it is not blocked from simplewall or tinywall but VPN worked when simplewall is disabled

**Comment by gettysburg** [comment]
I am not familiar with tinywall, they also do not make their source code public which to me is a bit suspicious, but according to several sources it also uses the WFP ("Windows Filtering Platform" API set), just like simplewall.

Have you tried completely disabling Windows Firewall? Right now you have 3 firewalls running, and this might cause problems, especially if two of them use the same API's.

You can completely disable Windows Firewall for all networks by opening the group policy editor, ``gpedit.msc``, as an Administrator, then navigating to ``Computer Configuration\Administrative Templates\Network\Network Connections\Windows Firewall`` (some more recent Windows versions call the last directory ``Windows Defender Firewall`` instead of just  ``Windows Firewall``).

In both the ``Domain Profile`` and ``Standard Profile`` folders, double-click on the rule named ``Protect all network connections``, and then click the checkbox named ``Disabled``. Apply and then click OK.

Here is how it should look if you did everything correctly:

![image](https://user-images.githubusercontent.com/2256003/162797952-040e2236-6ef8-4d1f-afa0-e45f59c961fe.png)

You really don't need Windows Firewall, and you can also disable the constant nagging from Windows.

> But when apps are selected only those rules are applied?

If no app is selected, the rule becomes a global rule, if one app or more are selected, the rule only restricts traffic for the selected app(s). This is also explained at the bottom of every tab of the rule editor.

> It says somethings are blocked it is not blocked from simplewall or tinywall but VPN worked when simplewall is disabled

What if you just run simplewall, unload all rules from tinywall and then close it? Now when you try to connect to your VPN, you should get a pop-up prompting you for a decision (which is likely your VPN server's remote IP, but make sure of that, I believe ProtonVPN allows downloading OpenVPN configuration files which contain the VPN server's IP and port).

Whitelisting these two, with the correct protocol (likely UDP) of course, should be enough.

Please correct me if I misunderstood anything, I think some sort of language barrier is making this harder than it needs to be :-(

**Comment by Rexadev** [comment]
Will those "global rules" also apply to apps with some other user rules specify applied to them

**Comment by Rexadev** [comment]
Maybe ProtonVPN uses some System Component and that needs to be allowed?

**Comment by gettysburg** [comment]
> Will those "global rules" also apply to apps with some other user rules specify applied to them?

I am actually not sure about this.

> Maybe ProtonVPN uses some System Component and that needs to be allowed?

The logger would show you that if that was the case, since I am not familiar with ProtonVPN, I advise you to drop the ProtonVPN client completely, and manually installing OpenVPN from [here](https://openvpn.net/community-downloads/), and then downloading the rule respective _.ovpn_ file as described [here](https://protonvpn.com/support/vpn-config-download/). Put the downloaded _.ovpn_ file in C:\Program Files\OpenVPN\config, then start the GUI for OpenVPN, and try to connect - enter your login details and you should see a popup from simplewall for an outgoing VPN connection by openvpn.exe.

**Comment by Rexadev** [comment]
Creating rule on per app basis is useless when no app is selected it a global rule
