### ISSUE TITLE
What Windows component is used for DHCP and other that is needed for connecting to WiFi.

### ISSUE THREAD

**Issue by Rexadev** [henrypp/simplewall#1192]

**Comment by gettysburg** [comment]
Hey Rexadev,

unfortunately none of my computers or servers run Windows 11, but.. have you tried a static IP?

Very easy to set up using the old control panel which you might remember from Windows 7, navigate to Network and Internet, then Network and Sharing Center, and click on "View network status and tasks", this should open a window, where, on the right side, you have the option to change adapter settings, this opens another window with a list of all network  cards, click the one you are trying to connect through, then click on Properties, select "Internet Protocol Version 4" in the list, and click on properties once again:

![image](https://user-images.githubusercontent.com/2256003/162634324-eb80e383-ed2e-4037-b24a-082dddf12767.png)

![image](https://user-images.githubusercontent.com/2256003/162634733-7c688ef9-14ba-4a24-b4cd-22691d8395af.JPG)

A bit hard to find, I know - now, pick your IPv4 address (make sure that no other device is using it already, your modems / routers DHCP server would likely rotate that devices IP in response, but no need for all that if it can be avoided), fill out the netmask and gateway settings (the gateway IP is almost always the IP you visit to configure your modem / router).

DNS is up to you, but I use Cloudflare's caching recursors at 1.1.1.1 and 1.0.0.1, when pinging them I get a reply after just 6 milliseconds, which is almost like having your own caching recursive resolver at home (except that CloudFlare offers a much better cache hit rate due to the amount of users using their service), and I still trust CloudFlare much more than Google.

Now, if you want to disable some unneeded features while you are already here, click on "Advanced", and then click on the WINS tab, then disable NetBIOS over TCP/IP and LMHOSTS lookups:

![image](https://user-images.githubusercontent.com/2256003/162634819-8485ad6a-b8e7-4268-a13f-480eb11a1d18.JPG)

This should get you a working connection, please report back.

>gettysburg

I think you tried to tag me here, but you forgot the @ sign in-front of my username, which is crucial.

Hope this works, and if not, maybe try fixing it on your own by using the logger or other tools like Wireshark?

✌️ 

I won't be available this evening, so good luck!

**Comment by Rexadev** [comment]
Thanks for answer but I have to set this up on someone else's computer.

**Comment by gettysburg** [comment]
That shouldn't matter, as long as they have working Internet they won't complain, I reckon.

**Comment by gettysburg** [comment]
That shouldn't matter, as long as they have working internet they won't complain, I reckon.
