### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by DomOBU** [henrypp/simplewall#1193]
In the "Packets log" screen, what are the white and green colours of the lines?

When I restarted today simplewall the "Packets log" was empty. Is it possible to keep the data for several days?

When I click on - (reduce/right corner of the screen) simplewall closes and the simplewall flame disappears from the taskbar. I have to restart simplewall. Is there a setting to prevent this?

**Comment by gettysburg** [comment]
Hey DomOBU,

> In the "Packets log" screen, what are the white and green colours of the lines?

the highlighting can be configured by opening the Settings (which are also accessible by pressing F2 as long as simplewall has focus), and then navigating to the "Highlighting" tab.

This is the default configuration:

![image](https://user-images.githubusercontent.com/2256003/162631483-48a1357f-3c78-4745-9a74-8331377f0c0b.png)

This means, that in the packet logger, blocked connections with a green background, were from applications with a code signing certificate (software publishers can sign their programs so that the user can verify that what they downloaded is indeed from said publisher, and hasn't been tampered with), connections with a white background are simply connections that don't match any criteria by the highlighter.

> When I restarted today simplewall the "Packets log" was empty.

The packets log, by default, is only cached in memory - you can however, choose to write it to any log file you want, and you can also set a maximum file size, the default being 1024kB / 1MB, which is plenty:

![image](https://user-images.githubusercontent.com/2256003/162631460-b53b02a1-9378-43d8-a18a-d21e6962a9cb.png)

> When I click on - (reduce/right corner of the screen) simplewall closes and the simplewall flame disappears from the taskbar.

This could potentially be a bug, what do you mean by "reduce / right corner of the screen)"?

The button called Minimize? 

If you hover over the buttons for a bit and don't move your mouse, an explanation text should appear. If you are indeed just minimizing simplewall, it should remain in your tray, especially since there is a configuration option named "Show confirmation dialog on exit", and it is **enabled** by default.

Once simplewall exits, do you notice signs of an application crash, such as the mouse pointer showing a spinning blue circle at the top right of it for a short period of time (2-5 seconds)?

You could also use Windows Event Viewer to figure out if your simplewall instance has crashed (**especially** if you noticed the blue, spinning circle), and provide us with the necessary debug information by following the instructions I posted in ticket #1188.

I don't want to sound rude, but please do not abuse the issue tracker for questions (generally, questions do not belong here at all) that you, with some time and common sense, could have answered on your own. I am currently pretty much the only one (with some rare exceptions) answering tickets on here trying to help people, and my time is limited.

Let me know what you find in relation to simplewall exiting without your consent.

✌️
