### ISSUE TITLE
Windscribe VPN compatibility

### ISSUE THREAD

**Issue by ltguillaume** [henrypp/simplewall#120]
When Windscribe VPN's Windows application loses the connection to the server somehow, it has Windows firewall entries in place to prevent any leaking traffic outside of the VPN connection. Traffic should be stopped by it until reconnected.

A short Wireshark test showed a lot of (unprotected) DNS requests as soon as the connection got cut off briefly.

My question is whether simplewall is completely compatible with programs that try to add temporary firewall rules. I used to think it is, as I can see rules in simplewall's log like `OpenVPN [Out]`, `WindscribeFirewall [Out]` and `WindscribeFirewall [Out-Loopback]`, but after the Wireshark test, I'm not so sure anymore. Could these rules also be made visible in simplewall?

**Comment by ltGuillaume** [comment]
So what I'm basically asking is whether an extra BFE can be handled correctly by another app while simplewall is running.

**Comment by ltGuillaume** [comment]
I just tried to block Internet Explorer from within simplewall, while Windscribe VPN was running. It. Did. Nothing. Internet Explorer was happy to load any page. It's as if simplewall's UI gets completely disconnected from WFP. When I shut down Windscribe, the firewall still wouldn't respond to my blocking of IE, even after retrying. When I restarted simplewall, all of a sudden stuff responded again and I could block and unblock IE instantly.

**Comment by ltGuillaume** [comment]
I can now confirm that restarting simplewall after a VPN connection has been made seems to fix the delays of popups, and the problem of the firewall not responding to checking/unchecking applications in simplewall's list.

It seems that there has to be some "reinitialization" of simplewall after Windscribe has (re)connected (which could be at any time).

Can/should I provide any more information in order to resolve this?

**Comment by ltGuillaume** [comment]
I can now confirm that restarting simplewall after a VPN connection has been made seems to fix the delays of popups, and the problem of the firewall not responding to checking/unchecking applications in simplewall's list.

It seems that there has to be some "reinitialization" of simplewall after Windscribe has (re)connected (which could be at any time).

@henrypp can/should I provide any more information in order to resolve this?

**Comment by ltguillaume** [comment]
For completeness, I have been using Windscribe and simplewall without any issues for years now. I simply forgot this issue wasn't closed yet.
