### ISSUE TITLE
SimpleWall not showing Apps

### ISSUE THREAD

**Issue by FrostBlade5** [henrypp/simplewall#1212]
Hey, i installed simplewall in a virtual machine and it works correctly showing all the installed apps and lets me allow or block connections while on my actual system it sadly does not show my installed programs, why is that and how can i fix it?

![simplewall issue](https://user-images.githubusercontent.com/91756004/164943882-c6e35cf2-71c2-4272-9989-1ecb6fcca77c.PNG)

**Comment by FrostBlade5** [comment]
![simplewall issue](https://user-images.githubusercontent.com/91756004/164943886-3cf703d0-9f8e-4884-a5b3-47c4e47a0a82.PNG)

**Comment by FrostBlade5** [comment]
Edit: my bad im an idiot i forgot to press "activate filter".
But i do have another question anyways when i klick activate filter, simplewall asks me to disable windows firewall, should i do that or can it be harmful for my security/privacy?

I have logitech ghub installed on my pc and i blocked outbound and inbound connections for this software via windows firewall, meaning if i disable windows firewall im worried the software can communicate again, or can i simply use simplewall to also block logitech ghub? i just want to make sure it's fully blocked!

**Comment by henrypp** [comment]
@Linkpod01

0x00000003 it is bullshit which is not displayed on MSDN, it is even cannot be returns:
The system cannot find the path specified.

**Comment by Linkpod01** [comment]
it means

**Incorrect Path:** The path you are trying to access may be misspelled or incorrect. Double-check the path for any typos.
File or Directory Does Not Exist: The file or directory you are trying to access may have been moved, deleted, or never existed.
**Permissions Issues:** You may not have the necessary permissions to access the specified path. Ensure that your user account has the appropriate permissions.
**Network Issues:** If the path is on a network drive, the network connection may be down, or the drive may not be mapped correctly.
**Environment Variables:** If the path is constructed using environment variables, ensure that those variables are set correctly.
To troubleshoot this issue, you can:

Verify the path you are using.
Check if the file or directory exists at that location.
Ensure you have the necessary permissions to access the path.
If applicable, check your network connection and drive mappings.
If you provide more context about where you are encountering this error (e.g., in a specific application, during a command line operation, etc.), I may be able to offer more specific advice.
-----------------
I believe this is due to a virus aftereffects... I had some problems with WinRAR saving passwords and other rights access troubles...
