### ISSUE TITLE
simplewall.exe cannot be blocked in v3.6.2

### ISSUE THREAD

**Issue by xesarni** [henrypp/simplewall#1216]
Is this intentional? Please revert it back.

**Comment by xesarni** [comment]
So it is a "feature". RIP simplewall.

**Comment by henrypp** [comment]
what feature? you made invalid configuration and name it "feature", mde

**Comment by xesarni** [comment]
Default configuration. Disallow simplewall.exe, accept the warning, hit refresh or restart simplewall and simplewall.exe will be allowed again.

**Comment by henrypp** [comment]
i fix this

**Comment by cloudgreen** [comment]
@xesarni Why would one disallow simplewall.exe, what is the purpose and consequence?

I am just curious, thanks! :)

**Comment by xesarni** [comment]
@cloudgreen I just prefer to block internet access for almost any app as much as possible due to hypothetical concerns about security and privacy.
Blocking simplewall.exe (and some other apps) is not recommended for a typical user as it may limit some functionality.

**Comment by cloudgreen** [comment]
@xesarni Ah, I get it, thanks!

First I thought "what's the point", but since the rules that Simplewall creates are created/hosted in WFP (and not in the application itself) then I can see point. 👍

**Comment by Pandaa-P** [comment]
It isn't fixed though.  

When you disable it a simple refresh (or restart) would move it to apps with internet access section. 

Also it's the only app that when you allow it through the [✓] check mark symbol does not warning you like it does with the other apps and move it to allowed apps silently, for example here Firefox when I [✓] check marked it to allow internet access, it give a warning.
![s1](https://user-images.githubusercontent.com/85793213/165644837-711f0121-720c-4c6f-8fd9-ad222a30e1b5.PNG)
Even though when the `Confirm when allowing application` option was marked [✓] check marked I don't see a confirmation window for simplewall.

Also it's the only app that complains when its lose internet access,  
![s2](https://user-images.githubusercontent.com/85793213/165645098-d149bf2f-9a0a-40e0-b99b-5381204e8dd2.PNG)
Even though when the `Resolve network addresses` option was [` `] uncheck marked, so there should be no addresses to resolve.

**Comment by gettysburg** [comment]
Tried to reproduce this bug on the latest build and it doesn't happen to me, also hasn't happened before.

**Comment by hho2002** [comment]
Add IsKeepUnusedApps=true To simplewall.ini
```
[simplewall]
IsKeepUnusedApps=true
...
```

**Comment by hho2002** [comment]
Add IsKeepUnusedApps=true to simplewall.ini
```
[simplewall]
IsKeepUnusedApps=true
```

**Comment by Pandaa-P** [comment]
@gettysburg I don't know man, I reinstalled it multiple times, after I purged it from registry, app data, temp folders and every other folder it may have residuals in and reinstalled it and again it show the same behavior. 

Also the `IsKeepUnusedApps=true` didn't work for me. I love simplewall but this is something I don't like.

**Comment by gettysburg** [comment]
Are you sure you restarted simplewall after adding the line to the config file, in the correct section?

I just tried again to reproduce this and still can't pull it off.

I gave simplewall full network access, checked for updates, revoked full networkaccess, re-applied rule sets and restarted the application, tried to check for updates and the requests got blocked, just as expected:

![image](https://user-images.githubusercontent.com/2256003/165859664-451468d1-86a2-4017-aa7d-7d34096942e3.PNG)

So, either you did some mistake when adding the line (I recommend using [Notepad++](https://notepad-plus-plus.org) instead of the built-in Notepad), or you have some other rule allowing the traffic through, or this is indeed a bug, but it needs a very specific configuration to be triggered.

🤷

**Comment by gettysburg** [comment]
Are you sure that you restarted simplewall after adding the line to it's config file, in the correct section?

I just again tried to reproduce this and still can't pull it off.

I gave simplewall full network access, checked for updates, revoked full network access, re-applied all rule sets and restarted the application, tried to check for updates and the requests got blocked, just as expected:

![image](https://user-images.githubusercontent.com/2256003/165859664-451468d1-86a2-4017-aa7d-7d34096942e3.PNG)

So, either you did some mistake when adding the line (I recommend using [Notepad++](https://notepad-plus-plus.org) instead of the built-in Notepad), or you have some other rule allowing the traffic through, or this is indeed a bug, but it needs a very specific configuration to be triggered.

🤷

**Comment by Pandaa-P** [comment]
Pretty sure did no mistake, and I tried with Notepad++ and it's the same. I noticed you use win11, I'm on windows 10 enterprise ltsc. it could be unique to windows 10 enterprise ltsc. 
There are no rules, even the vanilla clean install has this bug. I have no problem with simplewall has access, but I'm a paranoid person and this behavior just triggered my paranoia.

**Comment by gettysburg** [comment]
I don't use Windows 11, I use Windows Server 2019 LTSC (**mainly** because it lacks the bloatware that Windows 10 pre-installs, most notably the apps but also other stuff that was introduced with Windows 8, such as the Metro / Tablet desktop weirdness you get when pressing ESC or moving your mouse to a screen edge, I never got used to that stuff). 

Another reason is the fact that the Windows Server OS class counts as "Enterprise", thus unlocking many group policies and features that are unavailable on almost all, "regular" Windows installations, such as turning off telemetry / data collection completely, being able to uninstall Windows Defender and Smart Screen, as well as having the ability to turn off the (DWM mediated) forced V-Sync on windowed, hardware-accelerated Direct3D or OpenGL applications which otherwise would be forced to run at the refresh-rate of your monitor (which for me is 75 HZ, but this still introduces artificial input lag in games since most game engines depend on a high frame-count in order to poll input devices).

![image](https://user-images.githubusercontent.com/2256003/165872736-fcd56dce-981c-4e1d-a05f-d245561ae891.png)

So, our systems should pretty much match, Windows 10 LTSC is Kernel 1809 too as far as I know.

**Comment by gettysburg** [comment]
I don't use Windows 11, I use Windows Server 2019 LTSC (**mainly** because it lacks the bloatware that Windows 10 pre-installs, most notably the apps but also other stuff that was introduced with Windows 8, such as the Metro / Tablet desktop weirdness you get when pressing ESC or moving your mouse to any screen edge, I never got used to that stuff). 

Another reason is the fact that the Windows Server OS class counts as "Enterprise", thus unlocking many group policies and features that are unavailable on almost all, "regular" Windows installations, such as turning off telemetry / data collection completely, being able to uninstall Windows Defender and Smart Screen, as well as having the ability to turn off the (DWM mediated) forced V-Sync on windowed, hardware-accelerated Direct3D or OpenGL applications which otherwise would be forced to run at the refresh-rate of your monitor (which for me is 75 HZ, but this still introduces artificial input lag in games since most game engines depend on a high frame-count in order to poll input devices).

![image](https://user-images.githubusercontent.com/2256003/165872736-fcd56dce-981c-4e1d-a05f-d245561ae891.png)

So, our systems should pretty much match, Windows 10 LTSC is Kernel 1809 too as far as I know.

And trust me, being responsible for the whole IT infrastructure of a Fortune 500 company made me quite paranoid as well - however, I can still not reproduce your issue.

If you are familiar with the programming language C and Visual Studio in general, then you could try to build your own version of simplewall and debug it from there by using a tool such as [Windows Kernel Explorer](https://github.com/AxtMueller/Windows-Kernel-Explorer), it has full support for WFP data structures allocated by the Windows kernel. 

Due to time constraints I however will not be able to help you with either task, sorry - I still hope we somehow figure it out though.
