### ISSUE TITLE
Windscribe VPN IKEv2 Issue.

### ISSUE THREAD

**Issue by remodeler4187** [henrypp/simplewall#1249]
So while using this vpn I can't connect to ikev2 protocol (obv i enabled ipsec on system rules) If I let "svchost.exe" and "System" go through firewall it does connect but I don't want them to go through how can I solve this ?

something similar happened but I fixed it my own I will write it for more information, wireguard protocol didn't work as well but I solved it with adding a user rule [ss1](https://i.imgur.com/BlVghDb.png) [ss2 same port as built-in](https://i.imgur.com/BcuNsk4.png) (built-in dns rule didn't work).

Win 10 Pro 21H, Simpewall 3.6.3

**Comment by Cuddle0456** [comment]
Hi, I am the guy who opened this issue I lost that account cause I used temp-mail (pretty stupid of me) I fixed the issue by allowing internet access for "IKEEXT" on the services tab, since I can't access to other account someone should close this issue. Thank you gettysburg btw 

> there are multiple IPSec related services

Thanks to this answer I was able to solve the issue.

For other people might see this issue on the future after enabling "ikeext" also do not forget do enable "ikev2/ipsec" from system rules tab, peace.

**Comment by gettysburg** [comment]
Mark it as solved with your next answer so people searching for a solution can find it faster.

Also, good job, I did not even know that service existed!

Have a great weekend! 🏄

**Comment by Cuddle0456** [comment]
> Mark it as solved with your next answer so people searching for a solution can find it faster.
> 
> Also, good job, I did not even know that service existed!
> 
> Have a great weekend! 🏄

I edited the solving part I hope that will work since I can't access the op account this is the best I can do I guess. Thank you and have a great weekend as well !

**Comment by gettysburg** [comment]
Ah shit my bad, never mind then, I'll tag the admin to close it.

@henrypp

**Comment by Cuddle0456** [comment]
Before closing the issue I also want to add if these solutions doesn't work additionally you can make a user rule like this https://imgur.com/a/XOu0HAP this will work (do not forget to apply other solutions as well and make this user rule a separate one otherwise won't work).

**Comment by gettysburg** [comment]
@Cuddle0456 I don't know why your comment was marked as spam, I will re-post it for you as I don't see it as spam, maybe it is a bit lenient allowing all outgoing traffic, but having not used the technology employed here, I'm not sure whether that is on purpose.

His original comment:

>Before closing the issue I also want to add if these solutions doesn't work additionally you can make a user rule like this:
> 
>https://imgur.com/a/XOu0HAP
> 
>This will work as long as you do not forget to apply other solutions as well and make this user rule a separate one otherwise won't work.

All the best.

**Comment by gettysburg** [comment]
Now my comment is marked as spam as well, Henry - I tried to donate a sum of money close to the minimum wage of your country to your  **PayPal** account yesterday but your account kept refusing my payment.

Now with this repeated useless flagging of comments, I won't donate donate the sum to you by **IBAN**, as planned, @henrypp.

If you think something is "spam", EXPLAIN WHY when tagging - if you own a repository and don't even have the time or will to do that, then just give up, as people will leave and this place will become more rotten and deserted than it already is.

I tried to fix that by working with people, and giving them instructions, and in most cases, it helped them.

If my help is unwanted, tell me and I will stop contributing.

- gb

**Comment by gettysburg** [comment]
Now my comment is marked as off-topic as well, Henry - I tried to donate a sum of money close to the minimum wage of your country to your  **PayPal** account yesterday but your account kept refusing my payment.

Now with this repeated useless flagging of comments, I won't even try to donate the sum to you by **IBAN**, as planned, @henrypp.

If you think something is "spam" or "off-topic", EXPLAIN WHY when tagging - if you own a repository and don't even have the time or will to do that, then just give up, as people will leave in anger and frustration and this place will become even more rotten and deserted than it already is.

I tried to fix that by working with people, and giving them instructions, and in most cases, it helped them.

Re-posting a piece of useful information that could otherwise easily been missed by people is NOT off-topic.

If my help is not wanted, tell me and I will stop contributing.

-gb

**Comment by Cuddle0456** [comment]
> 



> Now my comment is marked as off-topic as well, Henry - I tried to donate a sum of money close to the minimum wage of your country to your **PayPal** account yesterday but your account kept refusing my payment.
> 
> Now with this repeated useless flagging of comments, I won't even try to donate the sum to you by **IBAN**, as planned, @henrypp.
> 
> If you think something is "spam" or "off-topic", EXPLAIN WHY when tagging - if you own a repository and don't even have the time or will to do that, then just give up, as people will leave in anger and frustration and this place will become even more rotten and deserted than it already is.
> 
> I tried to fix that by working with people, and giving them instructions, and in most cases, it helped them.
> 
> Re-posting a piece of useful information that could otherwise easily been missed by people is NOT off-topic.
> 
> If my help is not wanted, tell me and I will stop contributing.
> 
> -gb

I am kinda new to github for opening issue posts, Are you sure the admin himself tagged our comments as spam/off-topic maybe a bot did automatically I am not sure since my account created recently and I commented right away it sounds possible to a bot to mark is as spam but I have no clue about your case.

**Comment by gettysburg** [comment]
I as a 10 year old GitHub user can not do it, and he has no moderators as far as I know, so I think it was him.

**Comment by gettysburg** [comment]
I as a 10 year old GitHub user can not flag people as spam or off-topic, and he has no moderators as far as I know, so I think it was him.

**Comment by gettysburg** [comment]
Even I with a 10 years old GitHub user can not flag comments as spam or off-topic, and he has no moderators as far as I know, so I think it was him.
