### ISSUE TITLE
Does the "Enable network access" checkbox allow both outbound and inbound connections?

### ISSUE THREAD

**Issue by ShaunTheQuietGamer** [henrypp/simplewall#1255]
With the default rules that block inbound and outbound connections, does allowing a connection (either through a notification, or by checking the "enable network access" box) allow *both* outbound and (unsolicited) inbound connections, or just outbound, and solicited inbound connections? (meaning responses to outbound connections.)

Edit: Sorry if this is a dumb question, I barely understand any networking stuff, and I'm in the process of attempting to understand it all.

**Comment by gettysburg** [comment]
If default settings are sin use (Block all Inbound / Outbound), then the check mark will overwrite it, so use it sparingly, as it allows full, unrestricted access.

Please close this "issue" with your next comment, I've been trying to fight questions vs legitimate bug reports for a while now.

Have an awesome day.

**Comment by gettysburg** [comment]
If default settings are in use (Block all Inbound / Outbound), then the check mark will overwrite it, so use it sparingly, as it allows full, unrestricted access - which sometimes can be useful, especially for torrent-like clients, where creating user-rules is just not practical.

Please close this "issue" with your next comment, I've been trying to fight questions vs legitimate bug reports for a while now.

Have an awesome day.

**Comment by gettysburg** [comment]
If default settings are in use (Block all Inbound / Outbound), then the check mark **will**
overwrite it, so use it sparingly, as it allows full, unrestricted network access - which sometimes can be useful, especially for torrent-like clients, where creating user-rules is just not practical.

Please close this "issue" with your next comment, I've been trying to fight questions vs legitimate bug reports for a while now.

Have an awesome day.

**Comment by oklokl** [comment]
![1](https://user-images.githubusercontent.com/1571600/176795203-f554bc02-7a93-4e6d-b9d4-74dd8bcdae5e.png)
![2](https://user-images.githubusercontent.com/1571600/176795210-1ea6e76b-f9ca-4ada-89a4-740984cbe6df.png)
![3](https://user-images.githubusercontent.com/1571600/176795212-f74d00f7-bc6a-43ec-8457-1f6d74aebb49.png)
![4](https://user-images.githubusercontent.com/1571600/176795213-0098ff1e-272b-4152-abf1-325df1c2229d.png)
![5](https://user-images.githubusercontent.com/1571600/176795215-7d891b9b-f0d7-4143-95de-e9993132bb95.png)

This is my rule list.
I mostly accept https.
All games are allowed.
Because registration rules do not come out in the beginning.
I have to manually register process rules.

https://youtu.be/9Sm6ry34bwo
This is my initial registration.
I have this rule and it works well.

Too difficult for beginners.
I don't speak English so google translate
