### ISSUE TITLE
windows update doesn't work without having to allow svchost.exe

### ISSUE THREAD

**Issue by Cuddle0456** [henrypp/simplewall#1262]
windows update service and windows update delivery service from system rules doesn't work even allowing wuauserv from services tab doesn't work, How can I update windows without allowing svchost.exe through firewall Is there any work around ?

Edit: Time sync doesn't work either I think there is something wrong with system rules, I tried enabling NTP system rule and W32Time from services no luck for time sync either.

**Comment by gettysburg** [comment]
Tried allowing `wuauserv`?

**Comment by gettysburg** [comment]
These services just install updates, the Update Orchestrator service is the one that downloads them.

Try whitelisting `UsoSvc` in the services tab and it should work.

**Comment by gettysburg** [comment]
These services you mentioned just install updates, the Update Orchestrator service is the one that downloads them.

Try whitelisting `UsoSvc` in the services tab and it should work.

**Comment by gettysburg** [comment]
These services you mentioned just install updates, the Update Orchestrator service is the one that downloads them.

Try whitelisting `UsoSvc` in the services tab and it should work.

Regarding time sync,, I just selected a random NTP server and whitelisted it with a user rule, but the built-in rule should work, maybe it's IP can't get resolved or you have a typo somewhere - hard to tell over the internet.

**Comment by gettysburg** [comment]
These services you mentioned just install updates, the Update Orchestrator service is the one that downloads them.

Try whitelisting `UsoSvc` in the services tab and it should work.

Regarding time sync, I just selected a random NTP server and whitelisted it with a user rule, but the built-in rule should work, maybe it's IP can't get resolved or you have a typo somewhere - hard to tell over the internet.

**Comment by oklokl** [comment]
I'm working on a windows bug like this.
ms doesn't manage watch server well so bugs happen
Changed to google and never had any bugs.

`REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers" /v 0 /t REG_SZ /d "time.google.com" -F
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers" /ve /d "0" -F
REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters" /v NtpServer /t REG_SZ /d "time.google.com,0x9" -F 
net start w32time
w32tm /resync /nowait `

And this is my setup.
![23](https://user-images.githubusercontent.com/1571600/178710633-376322c3-9acd-4de8-a456-de2bf6619a1d.png)
![34](https://user-images.githubusercontent.com/1571600/178710763-02b5feb7-526a-4406-a5e7-d43ef41e745a.png)
And you shouldn't block ms. Can't update.
Advanced users do not need to update, but regular users are recommended to do security update.
I don't speak English, so I use google translator.

**Comment by gettysburg** [comment]
@Cuddle0456 There are a few other services used during the download of an update, it would be best to look at the logger and `services.msc` to find all possible candidates, then enable all of them at the same time.

Are you sure you did that?

The block lists might also be interfering.

Giving full access to `svchost.exe` is a potentially very bad idea, since many instances run under the `NT AUTHORITY\SYSTEM` account, one zero day exploit and an attacker would have full access to your system, without you even noticing.

If you don't, I will figure it out and post a tutorial.

**Comment by Cuddle0456** [comment]
> There are a few other services used during the download of an update, it would be best to look at the logger and `services.msc` to find all possible candidates, then enable all of them at the same time.

> Are you sure you did that?

Yes this sometimes works sometimes not I need a stable fix that will work everytime.

> The block lists might also be interfering.

I don't think so user/system rules should overwrite them.

> Giving full access to `svchost.exe` is a potentially very bad idea, since many instances run under the `NT AUTHORITY\SYSTEM` account, one zero day exploit and an attacker would have full access to your system, without you even noticing.

Yes I know that is why I opened this issue, also I would never give full access to svchost I only give it a time limited access however if I can find a fix that won't happen either. 

> If you don't, I will figure it out and post a tutorial.

I would really appreciate that it looks like I won't be able to fix it on my own.

**Comment by Cuddle0456** [comment]
@gettysburg I might have fixed the problem with this [user rule](https://imgur.com/a/nr0WsFR) Could you confirm that this fix works for you too ? Don't forget to disable other personal user rules (if you have) and block svchost.exe before trying this rule.

**Comment by oklokl** [comment]
However. Unfortunately if svchost.exe does not allow 443 https. Internet is not available.
It is involved in most services, even in the case of Windows Update. It is used through https http through svchost.exe. Blocking makes some internet unavailable or interrupted.
In my case it was. So I allowed https.
An error occurs because the NTP service is also not applied.

**Comment by gettysburg** [comment]
@ I did try that exact rule,  and still got loads of blocked connections, all stemming from various services. 

@henrypp

It would be very helpful if simplewall would also display the service name that tried to connect to the addresses in the logger.

This could be cleanly integrated by parsing the command line of `svchost.exe` and getting the `-s` argument.

![image](https://user-images.githubusercontent.com/2256003/179397250-3e8b18bd-8e4d-42af-b7f3-5cdac3d2ce6a.png)

@Cuddle0456 

Maybe download Process Hacker, disable the kernel driver as you won't need it and check for services that might be getting blocked, then trial & error until you found the right combination.

Since I am on a rather exotic system (Windows Server 2019 LTSC), there might also be differences in how updating is integrated - for example, I am missing quite a lot services when comparing my system to my friends system.

Anyway, good luck 👍

**Comment by gettysburg** [comment]
@Cuddle0456 I did try that exact rule, and still got loads of blocked connections, all stemming from various services, even when adding `UsoSvc` to the list of allowed services, although doing that significantly reduced the amount of blocked connections.

Here is the documentation on it from `services.msc`:

```Manages Windows Updates. If stopped, your devices will not be able download and install latest udpates.```

And yeah, that typo is from Microsoft - however this means that we are on the right track with whitelisting `UsoSvc`.

@henrypp

It would be very helpful if simplewall would also display the service name which got blocked from connecting somewhere.

This could be cleanly integrated by parsing the command line of `svchost.exe` and getting the `-s` argument and the following string, if it exists.

![image](https://user-images.githubusercontent.com/2256003/179397250-3e8b18bd-8e4d-42af-b7f3-5cdac3d2ce6a.png)

@Cuddle0456 

Maybe download Process Hacker yourself, disable the kernel driver since you won't need it then run it as Administrator it and check for services that might be getting blocked, then trial & error until you found the right combination.

Since I run a rather exotic system (Windows Server 2019 LTSC), there might also be differences in how updating is integrated - for example, I am missing quite a lot of services when comparing my system to my friends Windows 10 system.

Anyway, good luck, and let me know how it goes - I _might_ do some extra research later on if I have the time.

**Comment by Cuddle0456** [comment]
I fixed the issue with the user rule below I have been testing it for a few days and it seems pretty stable, if this rule doesn't work you allow wuauserv from services also or just add it to user rule.

![Windows Update Fix (1)](https://user-images.githubusercontent.com/108587502/179416103-c1130e1e-2faa-4a5d-8e74-5f858ff1f323.png)
![Windows Update Fix (2)](https://user-images.githubusercontent.com/108587502/179416104-e8b4e77c-869b-4ffa-8b1d-5b7244e614c1.png)
![Windows Update Fix (3)](https://user-images.githubusercontent.com/108587502/179416105-280a3270-ff74-4557-b7e6-f2ffbfbbd919.png)

**Comment by gettysburg** [comment]
That is far from a real fix, you just gave all services network permissions on TCP port 80 and 443.

You were meant to find the service which we are looking for all the time.

But, your computer, do whatever you want with it.

**Comment by Cuddle0456** [comment]
> That is far from a real fix, you just gave all services network permissions on TCP port 80 and 443.
> 
> You were meant to find the service which we are looking for all the time.
> 
> But, your computer, do whatever you want with it.

I even tried giving network access to all services from services tab even with that it does not work. The only way I found was this giving svchost tcp port 80 and 443, microsoft docs says that they used for windows update and if you are blocking microsoft stuff with internal blocklist no telemetry or other M$ shit won't go through according to packet logger. This is the most stable solution I could find If you have another **stable** solution I am open for it.

**Comment by henrypp** [comment]
It is already described here: #677
