### ISSUE TITLE
Add the feature to allow/block only the requested ip

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [henrypp/simplewall#1265]
Add for example an item in the Allow/Block submenu
![изображение](https://user-images.githubusercontent.com/4449851/180485780-7a1560da-f4a7-4d30-90b8-60d86115e5fc.png)

**Comment by 0x4E69676874466F78** [comment]
@gettysburg better UX. In the "allow" submenu it's more intuitive and lower access time.

**Comment by gettysburg** [comment]
What is the problem with opening the `Rules` drop down menu, then clicking `Create rule`, now you just have to change the action from the default, `Allow` to `Block,` and click save, takes less then 3 seconds for me and it blocks only the just now blocked request, using the IP address, not the resolved hostname.

**Comment by gettysburg** [comment]
What is the problem with opening the `Rules` drop down menu, then clicking `Create rule`, now you just have to change the action from the default, `Allow`, to `Block,` and click save. 

Takes less then 3 seconds for me, this will create a rule which blocks the IP address and port, not the hostname, if there is one.

I rest my case, this is already possible, with just 4 clicks, and it wouldn't help at all to add it to the popup, because then the next guy will come and ask for an option to only block or allow the requested port, and so on.

But maybe @henrypp has a different opinion on this :)

**Comment by gettysburg** [comment]
What is the problem with opening the `Rules` drop down menu, then clicking `Create rule`, now you just have to change the action from the default `Allow` to `Block` and click save. 

Takes less than 3 seconds for me, this will create a rule which blocks the IP address and port, not the hostname, if there is one.

I rest my case, this is already possible with only 4 clicks, and it wouldn't help at all to add it to the popup, because then the next guy will come and ask for an option to only block or allow the requested port, and so on.

But maybe @henrypp has a different opinion on this :)

**Comment by 0x4E69676874466F78** [comment]
@gettysburg my 2 click vs your 3 or 4 click (1 or 2 click is slow). If you need to allow a lot of addresses, then it's annoying.

**Comment by 0x4E69676874466F78** [comment]
Another problem is that each new created rule is made separate and is not added to the existing one.
![изображение](https://user-images.githubusercontent.com/4449851/183244944-a457bee4-b169-442e-8fca-3cd9e0bc7a7e.png)

**Comment by 0x4E69676874466F78** [comment]
@gettysburg cool, yeah?
![изображение](https://user-images.githubusercontent.com/4449851/183246946-3817dd48-3da4-4938-a7f7-89f1ebfa2c3c.png)

**Comment by gettysburg** [comment]
As I said, wait for Henry to decide but I agree - for your use case, a better solution would be needed.

**Comment by gettysburg** [comment]
I agree - for your use case, a better solution would be needed.

You could also create one user rule allowing all the IP addresses you need, and then disable notifications, so the other, new ones are silently blocked.

**Comment by 0x4E69676874466F78** [comment]
Hey, thanks but looks like you did something wrong. It continues to produce rules or how to use it?

**Comment by 0x4E69676874466F78** [comment]
@henrypp I would like ip to be added to rule remote for an already existing application rule.

**Comment by 0x4E69676874466F78** [comment]
@henrypp please reopen. And see https://github.com/henrypp/simplewall/issues/1265#issuecomment-1207189910

**Comment by eugenesvk** [comment]
> Another problem is that each new created rule is made separate and is not added to the existing one.

yes, there should be a button "add ip to the lock list of an existing rule" that would just add that single ip to the rule instead of multiplying all the rules

**Comment by gettysburg** [comment]
Can you stop necro-fucking this thread?
