### ISSUE TITLE
3.6.6 x64 Blocks without notice

### ISSUE THREAD

**Issue by debobrov** [henrypp/simplewall#1277]
On the example of program ESET Online Scanner (antivirus scanner) - traffic is blocked, despite the settings, the program does not notify about what is happening. There are no entries in the simplewall_debug.log about this, absolutely zero.
I turn off simplewall and the problem disappears.
My last topic was closed, but the problem remained after the change of two recent versions.

**Comment by henrypp** [comment]
Any entries in packets log?

**Comment by debobrov** [comment]
For some reason, I never have entries in the package log.

**Comment by gettysburg** [comment]
Please provide more information about your system, i.e. what exact Windows version and build so we can, if required, debug / reverse engineer these issues using the kernel and usermode libraries (and their respective symbols) that your system is using.

You can provide this information by opening `winver.exe` from the Start menu and taking a screenshot of it by using the `Snipping Tool` (use the mode `Window Snip`).

The screenshot is automatically copied into your clipboard, from where you can then upload it on here by simultaneously pressing CTRL + V.

Thank you.

**Comment by gettysburg** [comment]
Please provide more information about your system, i.e. what exact Windows version and build you are running so we can, if required, debug / reverse engineer this issue using the kernel and usermode libraries (and their respective symbols provided by Microsoft) that your system is using.

You can provide this information by opening `winver.exe` from the Start menu and taking a screenshot of it by using the `Snipping Tool` (use the mode **Window Snip**).

The screenshot is automatically copied into your clipboard, from where you can then upload it on here by simultaneously pressing CTRL + V.

Thank you.

**Comment by debobrov** [comment]
Windows 10 Pro x64 / 10.0.19044.1889 (Win10 21H2 November 2021 Update)

**Comment by paradoxministry** [comment]
I'm having the exact same issue on Windows 10 21H2 (OS Build 19044.1889). New apps do not show the notification window to allow them through simplewall and the packet log is empty.

**Comment by gettysburg** [comment]
Hi @paradoxministry, all that simplewall does is change WFP (Windows Filtering Engine) rules, by tapping "Disable filters" and then uninstalling it you have already made undone all changes by simplewall.

This seems like an issue with the WFP API itself on your specific version of Windows.

Please wait for the developer to look into it.

@henrypp

**Comment by paradoxministry** [comment]
I am aware that all simplewall is doing is using the WFP API which is why I brought up the fact that it was working fine before Windows updates and security patches.

I'm happy to report that I managed to fix the issue on my own machine by re-installing Windows on top of my existing installation, keeping my files and apps intact. I tried a few different approaches but nothing worked except for a re-install.

It's strange but it is what it is, something in Windows in either the registry or system config must have been corrupted or changed such that WFP notifications were no longer being displayed.

<img width="359" alt="simplewall_notifs" src="https://user-images.githubusercontent.com/326654/188993483-919b7c28-da67-4497-aaf4-72ed87a3400c.png">

**Comment by gettysburg** [comment]
Weird, but I'm glad you got it fixed, even if I wanted to find the reason for that, reinstalling just to get their firewall working is not an option for many users, considering all the customization's and changes I had to do after installing my OS before I was satisfied with it.

Your full Windows version string did not change by any chance?

**Comment by paradoxministry** [comment]
No, I can confirm the exact same build version is present after the reinstall. Initially I had done an upgrade from 1809 and hadn't noticed the notifications stopped appearing for quite some time, just noticed some apps started misbehaving, especially new apps.

**Comment by gettysburg** [comment]
I guess we can rule out changes to the usermode WFP API then, but thinking about it now , Microsoft has always been somewhat conscious of not breaking essential programming interfaces.

Guess it was just one of those Windows things, then, which either go away if you:

1.) Turn it off and on again.
2.) Re-install the OS.

Generally, I can't reproduce most bugs reported here, but that might be because I don't use a consumer version of Windows anymore, after Windows 7 support expired, I switched to Server 2019, which doesn't get the ludicrous amount of updates consumer Windows 10 gets, even while at it's core, still being based on the Windows 10.0.17763 1809 kernel. Other nice features are complete control over your OS, no annoying apps, and a user interface that is somewhat usable for production usage.

**Comment by gettysburg** [comment]
I guess we can rule out changes to the usermode WFP API then, but thinking about it now , Microsoft has always been somewhat conscious of not breaking essential programming interfaces.

Guess it was just one of those Windows things, then, which either go away if you:

1.) Turn it off and on again.
2.) Re-install the OS.

Generally, I can't reproduce most bugs reported here, but that might be because I don't use a consumer version of Windows anymore, after Windows 7 support expired, I switched to Server 2019, which doesn't get the ludicrous amount of updates consumer Windows 10 gets, even while at it's core, still being based on the Windows 10.0.17763 / 1809 kernel.

Other nice features are complete control over your OS, no annoying apps, and a user interface that is somewhat usable for production usage.

**Comment by cospking** [comment]
@debobrov Are you on **Windows 11** and using something like **ExplorerPatcher**? I noticed while using that I wouldn't get any of the pop-ups, after uninstalling **ExplorerPatcher** the pop-ups appear again.


Not sure if this is the same for **Start11** or **Startallback** but it did happen with ExplorerPatcher installed.

**Comment by debobrov** [comment]
I'm not sure that the events are somehow connected, but once I tried to change the explorer context menu (which appears when you right-click) using WinaeroTweaker - removing some items.

The program is not portable and has no effect on pop-up notifications, only on the contents of the menu.

**Comment by cospking** [comment]
> I'm not sure that the events are somehow connected, but once I tried to change the explorer context menu (which appears when you right-click) using WinaeroTweaker - removing some items.
> 
> The program is not portable and has no effect on pop-up notifications, only on the contents of the menu.

ExplorerPatcher hooks into a .dll-file (or replaces it), not sure how WinAeroTweaker works, but perhaps you could see if reverting these changes and disabling/removing it has any effect? As far as I'm aware WinAeroTweaker only changes things in Settings/Registry but I could be wrong.

The only changes I made with ExplorerPatcher was reverting the taskbar to W10 one to allow ungrouped open applications and it stopped showing me notifications from SimpleWall. As soon as I uninstalled it, the pop-ups started showing again.

The only other possibilities I can think of are things that have desktop overlays, change the themes/wallpapers etc. but obviously this is all farfetched, you could try to shutdown every application besides Simplewall and Eset virus scanner to see if it changes anything.
