### ISSUE TITLE
All UWP apps get blocked

### ISSUE THREAD

**Issue by orangebutblue** [henrypp/simplewall#1302]
For a couple of days now I've had UWP apps completely stop working. Not sure if it's a SW issue or (more likely) a Windows-problem (I'm having the same issue on Win10 and 11)

All UWP apps access get blocked - sometimes a SW prompt pops up (where I tell it to allow the UWP) sometimes no prompt shows up. In both cases network access gets blocked 

I've tried setting the "Microsoft Blocklist" (for all 3 categories) to Allowed, as well as Disabled. Doesn't work in both cases

Running SW 3.6.6

**Comment by YoBii** [comment]
I second this. Since updating to 3.6.6 (I think) I get pop-ups from Xbox UWP App all the time although it is already _allowed forever_ and the app does not work. 

I'm also wondering how I can use the Identifier Strings in _UWP Apps tab_ to identify entries that don't show a name when hovering over them.

**Comment by henrypp** [comment]
dup #1294
