### ISSUE TITLE
rules aren't saved. and other mess

### ISSUE THREAD

**Issue by Snus8bit** [henrypp/simplewall#1331]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

10

### Steps to reproduce

Hi! I just downloaded and tried it because of good reviews. Here is video of the first test: https://youtu.be/b1lYtRs65hI  

Steps
1. Open simplewall window-> apps tab. wait for any unknown app to connect.
2. In the network alert window click Rules. 
3. Go to "Rules" tab, check "Http" rule. click save
4. Observe that this application now exists in the "Apps with user rules" and a rule exists.
5. Click Refresh button.
6. Application now is in the "Apps without internet access" tab. (first bug)
7. Click "edit..." on this app and repeat step 3. Now it's ok, rules saved.
8. Go to "User rules" tab and see that "Enabled rules [for app]" exist.
9. Go to "Apps" tab and delete your app.
10. Go back to "User rules" tab click refresh. Now you have "enabled rules [for all]" that allows all outgoing http trafic. (second bug)

btw those sound notifications you hear are disabled too (third bug)

### Expected behavior

Expected on step 6 application to stay with rules.
Expected on step 10 not to allow http trafic for all apps

### Actual behavior

described in steps

**Comment by alterdaemon** [comment]
I confirm that there is a problem with HTTP Allow all apps rule under 3.6.7.
For no reason it can for itself enable HTTP for all apps when other app rules are changed, deleted added by user.

I spent 2 hours to figure out WTH is happening and there were some connections made which I never wanted to make.
I've lost a bit of confidence in the application after that.

I believe there may be many users who use 3.6.7 version and are oblivious that they have HTTP for all rule enabled because of this bug (!)

Please investigate, it looks like a serious incident.

**Comment by axel-1267** [comment]
Usually i block entire application, but i think this need better understanding.

**Comment by henrypp** [comment]
> Application now is in the "Apps without internet access" tab. (first bug)

Maybe you profile.xml is read-only or something else? Never meet this problem in all time.

> btw those sound notifications you hear are disabled too (third bug)

And where is here is bug? Disabled means you dono not hear it? OR just disabled itself?
