### ISSUE TITLE
[Question] How to whitelist all applications of the same name?

### ISSUE THREAD

**Issue by TrifarianGlory** [henrypp/simplewall#1335]
I have enabled the same apps dozens of times in whitelist mode because the path in C:\Windows\temp is always different. 
How to whitelist any exe that is named "intel-driver" permanently?

<img width="256" alt="whitelistmode" src="https://user-images.githubusercontent.com/49139121/199999965-a638dea2-a096-4b26-a69e-4d4392fd753c.png">

---

App version: v.3.6.7
Windows version: 10

**Comment by oklokl** [comment]
I've experienced it too.
There's no way. You need to temporarily disable the program.
In the case of a randomly generated temporary file, the program recognizes it as a new program exe, so there is no choice. Keep repeating indefinitely... Denying the internet.
Maybe someday the developers will improve it?
I hope too.

Same file though.
Since it is newly created, it is recognized as a different file.

**Comment by henrypp** [comment]
no way #853 #463
