### ISSUE TITLE
[Question] what is 'resolve network address' ?

### ISSUE THREAD

**Issue by mes-shahadat** [henrypp/simplewall#1359]
#### Can't connect to the internet if i enable both of this option :

settings -> resolve network address
blocklist -> microsoft update -> block

After booting to windows suddenly i can't connect to internet. I don't remember checking ' resolve network address' option and i noticed that after enabling both of this option, If i disconnect and reconnect my wifi, it shows (connected to WiFi, but) no internet connection.

#### Is there a blacklist mode in simplewall (where only the new/selected software will be alerted/blocked & everything else will be allowed) ?

can't use internet connection in windows sandbox or inside memu emulator. tried to allow many services but still not working.

---

App version: [3.6.7]
Windows version: Windows 10 Pro (22H2)

**Comment by Pandaa-P** [comment]
Just test on my end and I couldn't replicate your issue. 

Try resetting the setting of simplewall may solve it

>resolve network address

In simple terms, resolving a network address means finding the domain name associated with a particular IP address.
For example when an app try to connect to an IP, it's just a bunch of numbers and not understandable by human, but by resolving it you can read to which host the connections was.  

Here an example where I open my note taking app while enabling the resolve network address option. In the first image you can clearly see that it connect to GitHub server.

![image](https://user-images.githubusercontent.com/85793213/219144589-ee0bb26d-2b9d-48a4-8bd4-5bbe134b3871.png)

Here it doesn't show the domain name because I disabled the resolve network address option, only the IP it try to connect to. 

![image](https://user-images.githubusercontent.com/85793213/219144759-56ea8138-8ed1-446b-9776-a3dc71f1f2c1.png)

it's helpful option to know to which domain name your apps trying to connect to. 


>Is there a blacklist mode in simplewall (where only the new/selected software will be alerted/blocked & everything else will be allowed) ?

It's by default that only the new (not in the allowed list) apps will trigger a warning  


>can't use internet connection in windows sandbox or inside memu emulator. tried to allow many services but still not working.

You need to see what services they use and still blocked by simplewall.

**Comment by mes-shahadat** [comment]
> Try resetting the setting of simplewall may solve it

Currently it's working !. It must have been an mistake from my end. 

> It's by default that only the new (not in the allowed list) apps will trigger a warning

Well i assumed that maybe simplewall was also monitoring any new software / windows services installation and (when i click allow in simplewall prompt) it allows new softwares with it's windows services by default 😑. 

> You need to see what services they use and still blocked by simplewall.

Tried allowing many services but can't seem to solve it. It looks like i'm not good enough to use this tool (as i install some softwares irregularly), & Its a little hard for me to also locate and allow a service that is required by the software (and it's also really time consuming).

Anyway, Thank you for replying to my question.

**Comment by Pandaa-P** [comment]
>Tried allowing many services but can't seem to solve it.

Go to **services** tab and then sort by last date **added** to see the newly added services, put the mouse pointer over them one by one, when you put the mouse pointer over a service, a window will show up, and the first line of it will display the service location folder, your app (memu emulator) normally will have its services location in the same folder you installed it on. if you see a service that has the location in memu emulator folder, tick it box to enable its internet access.
