### ISSUE TITLE
[Question] How can I avoid repeated allow/block prompts after an application updates?

### ISSUE THREAD

**Issue by harveybolton** [henrypp/simplewall#1368]
SimpleWall is great and almost perfect for my needs, but I constantly get prompts asking me whether I want to allow or block applications that I have already allowed or blocked, most often it's a Microsoft one and the frequent offenders are "filecoauth.exe", "filesynchelper.exe", "microsoft.sharepoint.exe" and "msedgewebview2.exe". I believe it's because the path to these files changes after a windows update and SimpleWall/the windows filtering platform no longer recognises them as the same thing.

Here is a screenshot of the problem and an example path: [https://i.imgur.com/Zt4eHGf.png](https://i.imgur.com/Zt4eHGf.png)

From what I gather, wildcard paths will never be a thing with SimpleWall so my question is how can I permanently allow or block these? Please forgive me if this is already documented as I was unable to find it.

---

App version: 3.6.7 64-bit
Windows version: Win 11 Pro 22H2

**Comment by Pandaa-P** [comment]
Maybe `blocklist -> Microsoft applications -> allow` will solve it. I don't have a way to test it but I assume that will allow Microsoft apps with recognized digital signature to run without warning

**Comment by SvenBent** [comment]
Not asking Allowed after an executable has changed  is a security violation and defeats the purpose as an infected program  with a prior allow now has free access.

Block on the other hand could maybe just work on filename rather than file content to avoid keep blocking it

**Comment by harveybolton** [comment]
@henrypp Is this user error or a bug? I'm getting repeated prompts for executables such as filecoauth.exe, microsoft.sharepoint.exe, officeclicktorun.exe, msedgewebview2.exe, filesynchelper.exe

I just want to select "allow" or "block" for each and be done with it, but it looks like each time they update and the path changes slightly simplewall behaves as if it were an entirely new application and asks for my input which is getting quite annoying

I've looked for any way I can get around this other than just blanket enabling all Microsoft stuff but that defeats the purpose as taming the amount of apps from Microsoft that phone home is half the reason I installed simplewall

![image](https://user-images.githubusercontent.com/10099646/226745991-fe02d863-9493-449f-bbc0-24dec20b9c2f.png)

**Comment by RandomCoderFoxy** [comment]
I have exact same issue. I have Visual Studio 2022 installed. It downloads something at background and add an executable file to other directory so Simplewall prompt appears every time. Can Simplewall allow selected publisher? It would sort out my problem because publisher is the same for executables that i want to allow.

![simplewall](https://user-images.githubusercontent.com/38144952/230627204-df47c404-7878-43d4-ba32-37cb722679e2.png)

**Comment by henrypp** [comment]
You press block and then never gonna display notification again.

**Comment by harveybolton** [comment]
It still does show the notification again every time one of the applications updates regardless of whether I allow/block, because the path to the .exe changes slightly (e.g. C:\Program Files\Microsoft OneDrive\23.124.0613.0001\FileCoAuth.exe) SimpleWall behaves as though it's never seen it before and asks what I'd like to do. For a single app this would be tolerable but for many of the core Microsoft ones the popups are too frequent and annoying.

If it were possible to create rules with a slightly wider scope, this wouldn't be a problem. Examples rules that would fix this:

- Ignore the path: filename contains filecoauth.exe and signature contains Microsoft
- Wildcard the path: C:\Program Files\Microsoft OneDrive\*\FileCoAuth.exe

**Comment by skupjoe** [comment]
Agree with your solutions:
- relative path name or
- wildcard support for path name

Hoping we can keep FR #1441 open to plan some future work to implement one of these as a solution for repeated notifications.

**Comment by harveybolton** [comment]
@henrypp If you could acknowledge this as a problem and stop just closing these requests that'd be great

**Comment by noto10** [comment]
@henrypp 

I have also been faced with this problem since I started using Simplewall years ago. As an example, the following screenshot shows a Microsoft app (microsoft.sharepoint.exe) I want blocked:

![image](https://github.com/henrypp/simplewall/assets/13828004/85261dce-ad38-4591-b4dd-878c6889431c)

![image](https://github.com/henrypp/simplewall/assets/13828004/84984121-4d07-4b61-8414-91c44a8978bd)
_(I have deleted all previous instances of microsoft.sharepoint.exe in Simplewall to declutter and left only these, otherwise there would be hundreds of them)_

However, the app updates very frequently, averaging once every few days and the pop up alert comes on to tell me to **_Allow_** or **_Block_**. This has become tiring and repetitive. Surely there is a better solution as proposed by other posters in this thread and those pertaining to similar bugs eg.  #1425, #1426, #1729, #1727

Is there any better, more persistent and permanent way to block (or allow)?

@harveybolton Have you found any workaround?

**Comment by harveybolton** [comment]
I switched to Portmaster as @henrypp made it clear it wasn't something he planned on improving. I get that simplewall leverages the Windows Filtering Platform (WFP) and that probably doesn't support wildcards, but there's nothing stopping simplewall from processing a rule like: "IF filename contains filecoauth.exe AND signature contains Microsoft THEN add exception, ELSE prompt user"

It wouldn't need a complete re-write to use WFP in a different way and it's still far more secure than wildcarding allow rules, just a quick check to see if the user has pre-emptively OK'd this before prompting the user if they want to allow/block this app and silently add the rule to WFP accordingly.

Oh well, Portmaster works for me, Glasswire is probably another good alternative but thats paid.

**Comment by noto10** [comment]
> Portmaster

@harveybolton Thanks for replying. Had a look at Portmaster. It's very comprehensive. Do you find it resource-heavy compared to Simplewall? Truly hope that Simplewall could be improved in this area.

**Comment by Lordvader81** [comment]
It's evident that there are no intentions to tackle the issue. The same problem has been repeatedly pointed out in various posts by many users over more than a year, yet it persists. I understand that this is a free open-source application, but one would assume that such projects are initiated in the hope that they might evolve into a commercial product available through subscription or a one-time fee. However, with the persistent bugs in this application that remain unfixed, likely due to Henry's apparent arrogance, it seems unlikely.... Good Luck !!!

**Comment by YMan84** [comment]
I've been using Simplewall for years and it's one of the first applications I install on new systems, but this bug has been driving me crazy the last couple of months. After every reboot i have to re-block Teams, widgets.exe, or crossdeviceservices.exe and re-allow discord after every update. 

And after seeing the 6-7 different threads about this issue and similar problems and the refusal to acknowledge it as a problem I will be testing out Portmaster as well.

**Comment by skupjoe** [comment]
@henrypp come on man just support wildcards...
You can't tell me you've never experienced this issue either.

**Comment by avalnet** [comment]
This flat out ignoring of a glaring pain point for most users, probably the author themselves, for 2 years now, is one of the most ridiculous things I've witnessed. Congrats on being able to pretend this isn't an issue for that long :)

**Comment by filcuk** [comment]
This is a problem with most modern apps.  
I have to restart Fusion twice every time because **5 individual components are blocked** at runtime: node, authentication, webdeploy, streamer and the fusion exe itself.  
Power bi requires mashup containers and webview.  
Github requires the client and git remote.  
**Microsoft Defender requires whitelisting two exe's post-update** because it uses version folders

**Comment by avalnet** [comment]
> This is a problem with most modern apps. I have to restart Fusion twice every time because **5 individual components are blocked** at runtime: node, authentication, webdeploy, streamer and the fusion exe itself. Power bi requires mashup containers and webview. Github requires the client and git remote. **Microsoft Defender requires whitelisting two exe's post-update** because it uses version folders

It's unusable. I keep it disabled until I know I really need it to prevent some app from going online, or a new app so simplewall picks it up.

Literally defeats the purpose with how aggressive it is and having to keep it disabled...

**Comment by fantasygone** [comment]
It's happening to me right now after installing latest update

<img width="603" height="443" alt="Image" src="https://github.com/user-attachments/assets/46520465-8ac2-4d85-b4f3-cdbbb6c8519b" />

I keep receiving requests from svchost.exe and other stuff from Microsoft despite accepting.. what did you guys change?

**Comment by henrypp** [comment]
ok, go to new issue #2107

**Comment by bevels** [comment]
Dealing with it as well after the update. Spotify, Vivaldi, Nvidia overlay, mpdefendercoreservice, nvdisplay.container all keep displaying after clicking allow.

**Comment by RealismChicken** [comment]
> Portmaster

Does Portmaster have the same functionality as SimpleWall where it can block all connections by default and prompt you when programs try to connect? I can't seem to figure that out.

**Comment by eugenesvk** [comment]
> can block all connections by default and prompt you when programs try to connect? I can't seem to figure that

of course, settings → privacy filter → general → default network action → Prompt

**Comment by eusi** [comment]
@henrypp 

This is a major issue for apps using version-specific folders. Please keep this task open or link the active tracking issue. Is there a technical reason why wildcard or publisher-based rules are not planned?

It feels like I see this every day and have to press allow:

<img width="964" height="357" alt="Image" src="https://github.com/user-attachments/assets/f3870c7c-240a-4acc-8a50-33d573905ed0" />

**Comment by AnnanFay** [comment]
Why is this marked as a duplicate? I cannot find which ticket this is a duplicate of. 

> henrypp added duplicate and removed question on Jun 28, 2023

Also, if this is actually a duplicate, best would be to redirect users to the correct ticket / feature-request, then archive/lock this one and the other duplicates. Doesn't make sense to leave open real duplicate tickets.

**Comment by henrypp** [comment]
@AnnanFay сам поищи, я не помню, но здесь обсуждается правила по маске, а не повторяющиеся уведомления
