### ISSUE TITLE
[Bug] Apps can access Internet even when they are in the Apps without intenet access list

### ISSUE THREAD

**Issue by trythisd** [henrypp/simplewall#1422]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

Windows 10 21H2

### Steps to reproduce

Resume Windows from Hibernation.
Confirm apps should not have internet access (they are in the Apps without internet access list).
Perform internet requests from apps

### Expected behavior

Internet access should be blocked or simplewall should prompt.

### Actual behavior

Apps can access internet without prompting

**Comment by vasya-r7** [comment]
I`m not sure whether to create a separate bug report. For now I`ll write a comment here. As for me I monitor apps network activity via Sysinternal Process Monitor. I didn`t observe the behavior bug creator described but I observe two built-in Windows services which are not blockable by simplewall: AppXSvc(AppX Deployment Service (AppXSVC)) and gpsvc(Group Policy Client). Despite being blocked I observe traffic via Sysinternals Process Monitor.

Also to reliably block this services I`ve tried without luck svchost.exe hardlink trick. The trick is to create separate hardlink to svchost.exe for a service to be used as a separate binary file instead of svchost.exe. For example "svc_AppX.exe -> svchost.exe", "svc_gp.exe -> svchost.exe".

So blocking rule looks this way.

```
<item name="_ block svc_AppX_gp" dir="2" apps="AppXSvc|gpsvc|C:\windows\system32\svc_AppX.exe|C:\windows\system32\svc_gp.exe" is_block="true" is_enabled="true"/>
```

Windows version: 21H2(build 19044.1826)

![image](https://github.com/henrypp/simplewall/assets/48452558/f2c479b9-bf01-4e91-b66d-f93043fb36e3)

**Comment by vasya-r7** [comment]
Today ProcMon showed traffic from wmiprvse.exe which even not at apps list at all.
![image](https://github.com/henrypp/simplewall/assets/48452558/15b7f72d-6bd7-4138-a579-6221cbbf604a)

**Comment by arcv** [comment]
Same issue with 3.7.6 but this looks like rather settings error. Resetting simplewall settings blocks connection as it should. I thinkered with user rules before which may have enabled "allow connection all"

I suspect this is the settings allowed connections in profile.xml;

`<rules_config>
	<item name="HTTP" is_enabled="true"/>
</rules_config>`

`Edition	Windows 10 Pro
Version	22H2
OS build	19045.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0
`

**Comment by henrypp** [comment]
check ur fking rules
