### ISSUE TITLE
[Question]Is the program v3.7 safe to install- Virustotal flagged 6 antivirus vendors have detected virus?

### ISSUE THREAD

**Issue by Wepeemy** [henrypp/simplewall#1459]
Hi developer,

Usually, before I install the program, I always check with virustotal.com for any virus being detected.
Simplewall-3.6.7-setup ----> This was flagged with virus present in the program by 4 Antivirus vendors
Now the latest version: 3.7 ----> This was flagged with virus present in the program by 6 vendors.
See the link below. It seems like every new updates the detection by AV vendors has also increased.
https://ibb.co/JkvCNjH
https://ibb.co/thTxfXy

Are the detections classified as  false-positive?

Thank you.

---

App version: <v3.6.7 & v3.7>
Windows version: <Windows 10 Pro X64 Ver:21H2 >

**Comment by henrypp** [comment]
i dont care

**Comment by dethknite** [comment]
Yes it is clean. Many installers are detected as false-postives because:
1. installers are used for packing everything, including malware, making the packing and algos often false detections.
2. open source software generally isn't code-signed, because, let's be honest, there is no incentive to spend $300 a year to have a neat toy cert.

Fyi, the actual runtime shows fine in VT.
![spw](https://github.com/henrypp/simplewall/assets/965431/dbd67aa4-1173-4ae5-a370-1df25ef14093)

**Comment by debobrov** [comment]
> 2\. s

If in some versions of antiviruses created on the same basis (packaging) they do not find the virus, but in others they do, this is a reason to at least ask a question. It’s better to just change the program - since there have already been cases in history when the developer introduced viruses for various reasons (including when the developer’s site was hacked).
The point of a firewall is security, not blind trust.

**Comment by henrypp** [comment]
@debobrov

> including when the developer’s site was hacked

when?
