### ISSUE TITLE
Help file required for simplewall

### ISSUE THREAD

**Issue by aphextwins** [henrypp/simplewall#148]
I was curious as to what the following options do:

-Allow listen connections for all
-allow inbound connections for all

-Resolve network addresses

I hope someone can find the time to clarify this for me.

**Comment by ddd111ddd** [comment]
Simplewall could use some wiki and language/translation improvements. Many options are too open for interpretation or ambiguous, specially if you don't know much about how advanced networking works (like me).

We would need someone with solid english knowledge and a deep understand of how simplewall works to document it, and probably do some work with what terms are used in the english UI.

It's fine like it is and henrypp does a great job, I'm just saying that if we want to find areas to improve that would certain be one of them.

Unfortunately I don't have the skills required to do that, I contributed by helping translating to a certain language but the more technical parts are out of my skill range.

Also I think we should move this kind of discussion to a place like wilderssecurity forums so we don't bother henrypp too much 😄

**Comment by henrypp** [comment]
My engrish is very poor, i can explain some misunderstanded technical parts, and place it in compiled help (.CHM) file going with binaries (not online wiki) in current TBA release.

Now you need combine list of _all_ questions titles, and i try to answer with my low-skill engrish, someone who can help with powerfull words explain it for all other peoples.

**Comment by ddd111ddd** [comment]
I was thinking https://github.com/henrypp/simplewall/wiki could be used for that.

I'll try to help but like I said I don't have the required technical knowledge and my engrish sucks too.

_**1) Settings > General > Skip "User Account Control" prompt warning**_
What does it do? In what conditions is the UAC prompt triggered?

-------------------------------------

**_2) Settings > Rules >  Allow inbound connections for all
Settings > Rules >Allow listen connections for all
Settings > Rules >Allow loopback connections for all_**
How does the precedence works here? When this option is enabled, does it completely ignores any of the Rules? (Blocklist, System AND User) 
Does the app being in the Allowed or Blocked list changes the behavior?

-------------------------------------

**_3) Settings > Rules > Enable blocklist extra rules_**

This has potential for confusion because _Rules > Blocklist_ has some rules with the **extra_** prefix. The tooltip doesn't really explain much. I would just change it for something simple like "Enable Blocklist rules" or, if possible, even move the checkbox to the _Rules > Blocklist_ window itself. It's still somewhat confusing (or weird) but the quick toggle is a very nice option to have so it's worth it.

![blocklist](https://user-images.githubusercontent.com/1584331/37842465-fb0c2ee8-2ea0-11e8-841b-a1985308e47e.png)

-------------------------------------

**_4) Settings > Rules > Enable stealth-mode_**
This is a good example on how the tooltips can make things very clear. Good work.

-------------------------------------

**_5) Settings > Rules > Enable boot-time filters_**
This got me (and other people from what I can tell) confused since it looks like that Malwarebytes option to start the program earlier to improve the self-protection. But it was said before that the rules are always applied even when the UI is not there. So, what changes when this option is enabled? Who needs it and when? Tooltip says "prevents data leak during startup" so everybody is going to enable this option because "why would I want my data to leak?".

-------------------------------------

**_6) Settings > Rules > Advanced_**
Options are greyed out for me right now so I can't comment (2.2.1b).

**Comment by aphextwins** [comment]
> 6) Settings > Rules > Advanced
Options are greyed out for me right now so I can't comment (2.2.1b).
these options are greyed out when simplewall.exe is blacklisted or isnt whitelisted.

Even with the new tool tips, i still don't understand the implications of
-Allow listen connections for all
-allow inbound connections for all

**Comment by henrypp** [comment]
> Even with the new tool tips, i still don't understand the implications of
> -Allow listen connections for all
> -allow inbound connections for all
> -Resolve network addresses

Why do you need changing expert options? Are you expert?
