### ISSUE TITLE
doesn't work with win7?

### ISSUE THREAD

**Issue by msgtb** [henrypp/simplewall#1577]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 7

### Steps to reproduce

Installation on windows 7
Says it won't work with windows 7?

### Expected behavior

Should install on windows 7 machine.

### Actual behavior

It said you had to have windows 8.1.

**Comment by henrypp** [comment]
stop using this shit

**Comment by henrypp** [comment]
stop using this shit

**Comment by tamr** [comment]
> stop using this shit

Can I get back $20 paypal donation?

**Comment by henrypp** [comment]
@tamr it really not good idea, because it is fully OSS, and "stop using this useless shit" is means, why i need to support OS version that are already deprecated, w7 is not support more than 20% of features and i cannot understand why users use this? Are they in the stone age? Same for winxp, but someone still using this, lol
