### ISSUE TITLE
Handling existing rules or new filters

### ISSUE THREAD

**Issue by paradoxicallist** [henrypp/simplewall#162]
Does simplewall do anything to handle or disable already existing rules or new filters added by other programs once simplewall is activated?

**Comment by ltGuillaume** [comment]
I'd like to know more about this, too. simplewall used to disable the default Windows Firewall rule set, but this isn't allowed anymore in newer builds of W10. I cannot find any evidence of this anymore, even though it should at least do such a thing if it's to be reliable.

In contrast, it would be awful if simplewall discarded rules introduced via these ways:
- Services that try to use the Windows Filtering Platform as well, such as OpenVPN (to prevent DNS leaking) or Windscribe's firewall feature (to prevent any traffic outside the VPN connection)? These should absolutely be allowed to do their thing.
- Less high-priority: new filters added by other programs to the Windows Firewall via `netsh advfirewall`? Will they be discarded?

**Comment by ltGuillaume** [comment]
https://github.com/henrypp/simplewall/issues/167

**Comment by LucaPranay** [comment]
Greetings and appreciations!

Any chance of me finding some pre-made custom rules file, containing the nasty telemetry apps within windows that can ideally be blocked (and what should not be blocked eventually)? - because I really don't know what is ideal and what is not to be blocked (apps such as: ntoskrnl.exe, svchost.exe, sppextcomobj.exe, smartscreen.exe, sihclient.exe, runtimebroker.exe, rundll32.exe, msiexec.exe - so far I blocked them all, and system appears to be working well)

**Comment by henrypp** [comment]
@LucaPranay SW already have https://github.com/crazy-max/WindowsSpyBlocker in-app
