### ISSUE TITLE
[Question] How do I disable internet access for all apps - but allow LAN access for all apps

### ISSUE THREAD

**Issue by fliptoback** [henrypp/simplewall#1663]
Describe the question with as much detail as possible.

--- 
Hi there, thanks for such a useful app.

I am having trouble figuring out how to block internet access for all apps - but allow the apps to still access the local LAN network.

I tried to create a new rule such that it will block all Outbound traffic for Any protocol. If I enable this rule, it will block internet but I lose local LAN. What should I do to get local LAN access?

Thanks in advance. 

App version: <v3.7.6>
Windows version: <Windows 11>

**Comment by henrypp** [comment]
sw blocks all apps by default, do anything else is stupid

**Comment by fliptoback** [comment]
> sw blocks all apps by default, do anything else is stupid

But I lose local LAN access - how do i connect to my NAS for instance?

**Comment by henrypp** [comment]
im not a telepath

**Comment by dr04e606** [comment]
Allowing SMB on the System Rules tab did the trick for me.

**Comment by P1LeFR** [comment]
> Allowing SMB on the System Rules tab did the trick for me.

Sure, but it also opens a security risk. A user rule should address that instead of leaving SMB doors open.

SMB has long been a target for serious vulnerabilities. For example, exploits like EternalBlue (which was used to propagate the WannaCry ransomware in 2017) leveraged flaws in the SMB protocol. While patches have been deployed since then, older or improperly configured versions of SMB can still pose security risks.
