### ISSUE TITLE
The app crashes randomly after update to 3.7.7 version on windows 10

### ISSUE THREAD

**Issue by headzzzz** [henrypp/simplewall#1686]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

Windows 10 22H2 (build 19045.3803)

### Steps to reproduce

Randomly crashing application
[simplewall-1704305452.dmp](https://github.com/henrypp/simplewall/files/13822150/simplewall-1704305452.dmp)

![sw](https://github.com/henrypp/simplewall/assets/140740850/5af5f12e-348b-46a2-8df9-ca00473db95a)

Means: "The instruction at address 0x%p referenced memory address 0x%p. Unable to perform memory operation: %s. (0xC0000005)"

### Expected behavior

After crash, application is ended

### Actual behavior

Crashed

**Comment by privacyguy123** [comment]
Same

![image](https://github.com/henrypp/simplewall/assets/50337995/b8320dbf-9a46-4006-80dc-4e736f3e08df)

[simplewall-1704306556.dmp](https://github.com/henrypp/simplewall/files/13822192/simplewall-1704306556.dmp)

**Comment by henrypp** [comment]
now it fixed, sorry, [simplewall.zip](https://github.com/henrypp/simplewall/files/13822300/simplewall.zip)

**Comment by xp80** [comment]
same on win 11 edu 23h2 64 bit
[simplewall-1704531611.dmp](https://github.com/henrypp/simplewall/files/13848931/simplewall-1704531611.dmp)

[simplewall-1704531678.dmp](https://github.com/henrypp/simplewall/files/13848932/simplewall-1704531678.dmp)

**Comment by xp80** [comment]
error displayed is:
The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
Status: -1073741819 (0xC0000005)

hope it helps

**Comment by privacyguy123** [comment]
Still crashing after using in app update.

**Comment by henrypp** [comment]
i cant understand where it crashed if u dont get crash dump

**Comment by henrypp** [comment]
@privacyguy123  i cant understand where it crashed if u dont get crash dump

**Comment by Alcazer** [comment]
> now it fixed, sorry, [simplewall.zip](https://github.com/henrypp/simplewall/files/13822300/simplewall.zip)

in this version, open the connections tab then press home key and wait a bit. it crashed every time. maybe it can help

**Comment by henrypp** [comment]
@Alcazer it cant help, ONLY DUMP, SHIT

**Comment by hushkamala** [comment]
I only scroll up and down on connections tab. After a moment it crashes.

Dump:
[simplewall-1704652970.dmp](https://github.com/henrypp/simplewall/files/13854583/simplewall-1704652970.dmp)

**Comment by henrypp** [comment]
@hushkamala u not using  [fix](https://github.com/henrypp/simplewall/issues/1686#issuecomment-1875804560).

**Comment by hushkamala** [comment]
@henrypp I saw the fix, downloaded it, compared file hashes and they were the same... so i thought... long story short... now with the fix:

Crashed two times just scrolling through connections tab:
[simplewall-1704711131.dmp](https://github.com/henrypp/simplewall/files/13859089/simplewall-1704711131.dmp)
[simplewall-1704711188.dmp](https://github.com/henrypp/simplewall/files/13859091/simplewall-1704711188.dmp)

**Comment by henrypp** [comment]
@hushkamala
![sshot-001](https://github.com/henrypp/simplewall/assets/3902025/c3a0e8f2-c0ae-4542-9cad-13a47160e1a9)

orly? in ur dumps `ptr_app was nullptr` it CANT be happened, because it was checked it in [fix](https://github.com/henrypp/simplewall/issues/1686#issuecomment-1875804560).

**Comment by Alcazer** [comment]
> @henrypp I'm sorry but the first fix posted was really the same as 3.7.7 version. Or something is very wrong on my side. Downloaded it 3 times and checked not only crc32 hash. I apologize if the problem is my doing.
> 
> ![WinRAR_MAqW1Y0ap5](https://private-user-images.githubusercontent.com/72048073/294884839-1764e233-d838-4c43-83e6-6f11f5dc891f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTYwOTksIm5iZiI6MTcwNDcxNTc5OSwicGF0aCI6Ii83MjA0ODA3My8yOTQ4ODQ4MzktMTc2NGUyMzMtZDgzOC00YzQzLTgzZTYtNmYxMWY1ZGM4OTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEyMDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MTYwMTUxYWI1ZTUxMmIyM2E0NmY3ZWUzY2VkMzJjYjgyM2M5MWFhNWE1M2NmN2Y1YzczYzA3YmI2ZTViOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nzS5gNt0e6aGEwvvFS-1VchyBp2EbPfIpLYo5-xM_8w)
> 
> On this last fix it is not crashing for me. Thank you and sorry if the mistake is mine.

+1, i also checked it and not crashing

**Comment by nullptr-deref** [comment]
Actually, the very same crash happens for me when inside "Connections" tab.
[simplewall-1704844573.dmp](https://github.com/henrypp/simplewall/files/13881360/simplewall-1704844573.dmp)

**Comment by henrypp** [comment]
@nullptr-deref u complete not have eyes?

**Comment by nullptr-deref** [comment]
@henrypp wdym by saying such mean things? Issue is still open, fix is not being unpacked properly on my PC, found no way to somehow apply this patch to my installation of simplewall.

**Comment by henrypp** [comment]
@nullptr-deref u dont have 7zip, lol? and why it is my problem?

**Comment by nullptr-deref** [comment]
@henrypp since you are the owner and the leading maintainer of this very repository, I believe that it's most certainly your concern of delivering hot fixes & patches somehow properly, or at least provide somewhat like a quickfix instruction about what toolset one should use when posting fixes in such a manner.
There's loads of archivers on the market, and nobody (not even you) previously mentioned 7zip is a "must-have" in the discussion in question.

Nevertheless, I appreciate your effort you've put into developing simplewall.

Will inform if the issue is resolved for me.

**Comment by nullptr-deref** [comment]
After applying patch I'm still experiencing crashes while even idly watching into "Connections" tab.
So, yet another crash dump: [simplewall-1704898841.dmp](https://github.com/henrypp/simplewall/files/13889415/simplewall-1704898841.dmp)

**Comment by nullptr-deref** [comment]
After half an hour long observation seems like crash is now completely gone.

For the sake of complete clarity about unarchiving and installing the patch I'll mention once more that one shouldn't use default Windows zip utility but something like WinRAR or 7zip instead because Windows archiver can possibly treat archive as corrupt.

**Comment by henrypp** [comment]
@nullptr-deref it bcs github did not allow 7z or rar files (did not understand) to attach but this is 7z archive renamed to zip

**Comment by Cthululz** [comment]
Mine crashes everytime I open the Connections tab.
Simplewall v 3.7.7
Windows 11

**Comment by GY8VSdYYzvL8-K6T** [comment]
Does SimpleWall.exe.sig need an update to work with fixed version 3.7.7?

**Comment by Cthululz** [comment]
> @hushkamala i can only re-upload fix: [simplewall.zip](https://github.com/henrypp/simplewall/files/13859257/simplewall.zip)
> 
> there is nothing changed in SW except project sdk

sorry for dogpiling on just wanted to let you know that I'm running this now and it's not crashing anymore when i go to the connection tab

thank you

**Comment by henrypp** [comment]
@GY8VSdYYzvL8-K6T зачем?

**Comment by privacyguy123** [comment]
[simplewall-1705081552.dmp](https://github.com/henrypp/simplewall/files/13922439/simplewall-1705081552.dmp)

**Comment by henrypp** [comment]
@privacyguy123 u too cant <s>download</s> unpack [file](https://github.com/henrypp/simplewall/issues/1686#issuecomment-1880805690)

**Comment by privacyguy123** [comment]
> @privacyguy123 u too cant download unpack [file](https://github.com/henrypp/simplewall/issues/1686#issuecomment-1880805690)

Bug is with the new file, I'm not a retard.

**Comment by henrypp** [comment]
@privacyguy123 then why ur crash dump is [the same](https://github.com/henrypp/simplewall/issues/1686#issuecomment-1880800741)?

**Comment by privacyguy123** [comment]
> @privacyguy123 then why ur crash dump is [the same](https://github.com/henrypp/simplewall/issues/1686#issuecomment-1880800741)?

You tell me - the same crash is happening with the new .exe file.

**Comment by xp80** [comment]
> > @hushkamala i can only re-upload fix: [simplewall.zip](https://github.com/henrypp/simplewall/files/13859257/simplewall.zip)
> > there is nothing changed in SW except project sdk
> 
> > @henrypp I'm sorry but the first fix posted was really the same as 3.7.7 version. Or something is very wrong on my side. Downloaded it 3 times and checked not only crc32 hash. I apologize if the problem is my doing.
> > On this last fix it is not crashing for me. Thank you and sorry if the mistake is mine.
> 
> +1, i also checked it and not crashing

this fix worked for me

**Comment by henrypp** [comment]
@Rubber-Duckie no

**Comment by Rubber-Duckie** [comment]
> @Rubber-Duckie no

Trust inspiring

**Comment by TheArkive** [comment]
This fix worked for me.  Thanks.  I love this program.

**Comment by crash5** [comment]
Will there be a release from this fix?

**Comment by henrypp** [comment]
@crash5 soon, i hope

**Comment by henrypp** [comment]
@fernyjbh it crashed because of mnet.dll (sw did not interact with this shit), so, it does not my problem

**Comment by fernyjbh** [comment]
> @fernyjbh it crashed because of mnet.dll (sw did not interact with this shit), so, it does not my problem

I see, that dll is a midi rtp wireless app, sorry then

**Comment by Rubber-Duckie** [comment]
We all need to follow some basic best practices whcih avoid these situations.
Firstly, this could have been compensated for had their been unit text code coverage during unit testing. Mock out possible 3rd party libraries. If you have any code that interacts with third-party libraries, you must validate and check all the parameters in and out. Most 4GL languages do basic type checking, but you need to use strong typing for any custom structs or else parse them explicitly. This can prevent many exploits and exception cases. And don't forget, third-party libraries are not reliable, so you need to have good exception management around any call to them. If your application crashes because of poor exception handling, that's on you, not the third-party library. All you need here is a graceful way of handling exceptions from third-party dependent API calls. For example, the grid should omit data that was expected from the API call, not crash completely like a drama queen. I have to say, you do act like a drama queen and your code reflects that. https://gkovan.medium.com/build-to-manage-proper-exception-handling-makes-your-applications-easier-to-build-and-manage-9105dbaf2862

**Comment by Rubber-Duckie** [comment]
We all need to follow some basic best practices which will avoid these situations.
Firstly, this could have been compensated for had there been unit text code coverage during unit testing. Mock out possible 3rd party libraries. If you have any code that interacts with third-party libraries, you must validate and check all the parameters in and out. Most 4GL languages do basic type checking, but you need to use strong typing for any custom structs or else parse them explicitly. This can prevent many exploits and exception cases. And don't forget, third-party libraries are not reliable, so you need to have good exception management around any call to them. If your application crashes because of poor exception handling, that's on you, not the third-party library. All you need here is a graceful way of handling exceptions from third-party dependent API calls. For example, the grid should omit data that was expected from the API call, not crash completely like a drama queen. Also, a sensible message to the user to suggest they look at the exception log since something went wrong while doing XYZ. Use an exception logging framework. I have to say, you do act like a bit of a diva :D with your use of language. I guess your code reflects that. https://gkovan.medium.com/build-to-manage-proper-exception-handling-makes-your-applications-easier-to-build-and-manage-9105dbaf2862
