### ISSUE TITLE
Ask for permission for the same process over and over[Bug]

### ISSUE THREAD

**Issue by pralium444** [henrypp/simplewall#1729]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.8

### Windows version

Windows 11 24H2

### Steps to reproduce

every 10 or 30 minutes (can't say) Simplewall ask to authorize or block this process : 
C:\users\xxxx\appdata\local\temp\x2nbxfbr.m5m\resources\app\servicehub\services\microsoft.visualstudio.setup.service\backgrounddownload.exe

And also, eveytime discord updates itself, simpleWall prompts me for approval...and since Discord updates everyday...

Thanks !

### Expected behavior

not asking for appoval for the same process

### Actual behavior

ask for approval

**Comment by herrenP** [comment]
I don't think this is a bug since, I assume in both cases, the path to the exe file has changed. At least I know it does for Discord. But it would be great if there was an optional feature to check only the name of the exe file and disregard the path. Especially since there are a bunch of applications out there that does not implement a retry feature for network connectivity and then it does not work as expected and thus we need to restart the application after adding a rule in simplewall. Some installers do this for example. Super annoying.

**Comment by Lordvader81** [comment]
It's evident that there are no intentions to tackle the issue. The same problem has been repeatedly pointed out in various posts by many users over more than a year, yet it persists. I understand that this is a free open-source application, but one would assume that such projects are initiated in the hope that they might evolve into a commercial product available through subscription or a one-time fee. However, with the persistent bugs in this application that remain unfixed, likely due to Henry's apparent arrogance, it seems unlikely.... Good Luck !!!
