### ISSUE TITLE
[Question] What is the difference between Disable, Allow and Block?

### ISSUE THREAD

**Issue by Ehab-d** [henrypp/simplewall#1758]
Describe the question with as much detail as possible.

In Blocklist, what is the difference between `Disable`, `Allow` and `Block`?

If we assume that `Disable` doesn't do anything, then what's the point of having `Allow` if it won't do anything either?

![image](https://github.com/henrypp/simplewall/assets/129071698/63aa3112-e98b-4608-a61c-d1355aa923d0)

This is not considered a question! I wish you update the menu to be clearer because I and everyone I know didn't understand.

---

App version: 3.8
Windows version: Windows 11

**Comment by henrypp** [comment]
oh ,ur friends dont understand,and u create duplicate issue, it is very stupid, and there i understand

**Comment by Ehab-d** [comment]
> oh ,ur friends dont understand,and u create duplicate issue, it is very stupid, and there i understand

Sorry for the inconvenience, although I did nothing wrong. This didn't answer the question. This issue added the idea of making the menu more clear.

**Comment by henrypp** [comment]
it already clear if u dont idiot

**Comment by Ehab-d** [comment]
> it already clear if u dont idiot

Seriously... What is the difference between Allow and Disable?

**Comment by henrypp** [comment]
Seriously, u r idiot if dont understand alow and disable

**Comment by Lordvader81** [comment]
> Seriously, u r idiot if dont understand alow and disable

Typical Henry reply, arrogant and disrespectful as usual ...🤨

**Comment by Ehab-d** [comment]
> > Seriously, u r idiot if dont understand alow and disable
> 
> Typical Henry reply, arrogant and disrespectful as usual ...🤨

Sometimes I can't believe he is the developer of the great software.

**Comment by Lordvader81** [comment]
> > Typical Henry reply, arrogant and disrespectful as usual ...🤨
> 
> Sometimes I can't believe he is the developer of the great software.

Ya, I know .... But whatever 🤷‍♂️ .. Henry can eat a Dick.
I've recently switched to PortMaster, and I must say, it works wonderfully! It may not be as intuitive and user-friendly as Simplewall during the initial setup and installation, but once it's properly configured, it truly is a dream. Gone are the nagging screens for applications that have already been authorized. With the use of application wildcards and fingerprints, those annoyances are now a thing of the past!

**Comment by ferrlen** [comment]
Google picks this post as 1st option, so for anyone new:

I also had no idea of the difference, but this answer https://github.com/henrypp/simplewall/issues/1739#issuecomment-2048601278 makes me think that, given the options are in "Blocklists", and blocklists are a list of default addresses to be blocked, the options are:

- Allow: this blocklist will **override** your current firewall rules and **allow** connection for everything inside of them.
- Block: this blocklist will **override** your current firewall rules and **block** connection for everything inside of them.
- Disable: **disables** this blocklist, so that it will do nothing (it **won't override** any rules or set any rules). This is the only option that does nothing, as the other 2 will either allow or block everything in the blocklist.
