### ISSUE TITLE
[Enhancement] Add "autolearn mode" like TinyWall

### ISSUE THREAD

**Issue by adolfintel** [henrypp/simplewall#180]
One of the best things about TinyWall is the autolearn mode, which works like this:
* Enable autolearn mode
* Run some application (like Steam)
* It automatically adds Steam (and its related exe files that generated traffic) to the whitelist
* Turn off autolearn mode

This is the only thing that's stopping me and many others from switching to simplewall. If this feature is added, I'll be happy to recommend this project over TinyWall in my Windows privacy guide.

**Comment by aphextwins** [comment]
so autolearn is basically: While its on, add everything to the whitelist thats generating traffic?

**Comment by adolfintel** [comment]
Yes, it's pretty much like that. It's really useful for apps like Steam, Riot, Thunderbird, ... that have multiple exe files and you don't want to add them one by one.

**Comment by tokariu** [comment]
I strongly don't recommend autolearn mode!
This was already a problem with TinyWall. If you turn it on, your whole system is whitelisted and every program (not yet explicitely blocked) is able to connect out/in while you are maybe just seeking for a one specific app/exe. You might end up whitelisting apps you don't want to. Of course you can verify the whitelisted app during autolearn mode, but there is always a chance you miss something you don't want. 

Instead of introducing autolearn mode ala TinyWall, I strongly recommend fixing and enhancing the reliability of the current notification system. If the notification system catches every app correctly, there is simply no need for an autolearn mode. 
For example: when steam connects to the internet, it requires a few more executables to get whitelisted to work properly. Currently the notifcation system fails by either showing no notifications at all, or just for the steam.exe and not steamwebhelper.exe and others which are required for steam to work. Comodo firewall was rock solid when it comes to correct notifications (but sucks so much more on other levels), if Simplewall gets that rock solid too, there would be just no need for an autolearn mode.

**Comment by heforfree** [comment]
not good idea.keep it simple
better be simplewall scanner(seperate exe), scan drives for exe
show you window to allow wanted program then create and export rules
then import rule in simplewall

**Comment by henrypp** [comment]
@tokariu, @heforfree complete agree, autolearn mode for lazys.

**Comment by adolfintel** [comment]
How about whitelisting by clicking on a window? That was also a really useful thing

On 23 May 2018 06:29:39 CEST, Henry++ <notifications@github.com> wrote:
>@tokariu, @heforfree complete agree, autolearn mode for lazys.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/henrypp/simplewall/issues/180#issuecomment-391216734

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adolfintel** [comment]
I don't see how it's for lazy. By selecting a window you can know which process that handle belongs to (easy to do in c++) and you can show a dialog for that exe.

I understand your point about autolearn, I always have to make sure it doesn't whitelist something completely unrelated, but this seems very reasonable to me. Adding executables one by one is hated by most people.


On 23 May 2018 07:24:12 CEST, Henry++ <notifications@github.com> wrote:
>@adolfintel it's for lazys too, hard ("clicking on a window" means
>handler injection into explorer) integration into windows will not be
>implemented at all.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/henrypp/simplewall/issues/180#issuecomment-391224217

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by henrypp** [comment]
@adolfintel, it's both useless, because simplewall already have notifications and simplification of this feature is not on my way.
