### ISSUE TITLE
SimpleWall Crashing on Win10x64

### ISSUE THREAD

**Issue by MCHALAO** [henrypp/simplewall#25]
Hi, Henry:

Sorry to report this, but simplewall (1.46) crashes and is shut down by Windows every time I try to run it. I am running on a BPortuguese Windows 10 x64 1607 14393 1066 edition, NVidia GE Force 2GB, 8GM RAM, Asus MB.
Thanks for your dev efforts.
Regards.

**Comment by Lichtenshtein** [comment]
+ Crashes when i try run it with my 91mb custom rules file.

**Comment by henrypp** [comment]
@MCHALAO, 1.4.6 is old version, try for latest 1.5.5.
@Lichtenshtein, OH SHI~, can you upload this 91mb cutom rules file, need for test.

**Comment by Lichtenshtein** [comment]
https://yadi.sk/d/MD6lkA8y3JEpop

**Comment by henrypp** [comment]
@Lichtenshtein ohh.. simplewall cannot parse 91mb and crashing, because do not have memory enough. notepad need more than 1 minutes for parse file and display it (with freeze).

i think maximum size is 20mb with 4gb ram, but app still work with freeeeeeeeeeeeezee.

in near future i will do something with that.

**Comment by John3** [comment]
I have Windows 10 Enterprise N 2016 LTSB and works ok with SFv1.6.5.

**Comment by henrypp** [comment]
@Lichtenshtein, v2.x optimized memory usage and now you can load large xml files, but parsing is still freeze UI - there are no solution!
