### ISSUE TITLE
Notifications open too late or never

### ISSUE THREAD

**Issue by Distelzombie** [henrypp/simplewall#256]
Hi

I found that Notifications appear very late, all the time. (10-30s delay)
Also, if two applications are blocked at the same time and both produce (or should) notifications, only one notification is shown.

best regards

**Comment by Tom4tot** [comment]
I have the same issue, it seems to concern all apps. I'm running Windows 10 1809.

**Comment by Distelzombie** [comment]
Oh sorry: Windows 10 pro 1803
Sometimes they don't even bother to show up at all until I manually add the program.

**Comment by Tom4tot** [comment]
Hi, thank you for your last update and for your hard work.

However, even after a clean install (portable version), I still have delays with notifications. I'd say it's most of the time 5-15 seconds. For me they always eventually arrive, just with a little delay. It's not a huge issue honestly but I just wanted to give you some feedback.

**Comment by henrypp** [comment]
@Tom4tot, delays for notifications (5-15 seconds) is normal thing, because simplewall used only one thread to parse all dropped packets queries pool, and delay depends on simplewall settings (network address resolver, check apps signature and some another more).

**Comment by Distelzombie** [comment]
This still happens for me sometimes. I even unchecked resolving addresses and signatures.

**Comment by henrypp** [comment]
@Distelzombie how late is it?

**Comment by Distelzombie** [comment]
Sometimes it never appears.
Just now with whois64.exe from sysinternals the notification never appeared. Only AFTER I added and allowed it myself a notification popped up asking about access to 127.0.0.1 - but it was already allowed.

Again, I have "resolve domain names" and "check signatures" already disabled.

**Comment by MrX-at-GitHub** [comment]
Still happening on 2.3.11

Now, in order to bring up a notification I close main gui and relaunch again but a new error shows in the logfile:
‎23-‎Dec-‎18 ‏‎10:27:03 AM,FwpmEngineSetOption(),0x00000005,FWPM_ENGINE_COLLECT_NET_EVENTS,2.3.11
‎23-‎Dec-‎18 ‏‎10:27:07 AM,FwpmEngineSetOption(),0x00000005,FWPM_ENGINE_COLLECT_NET_EVENTS,2.3.11
‎23-‎Dec-‎18 ‏‎10:27:07 AM,FwpmTransactionCommit(),0x00000005,#2123,2.3.11
‎23-‎Dec-‎18 ‏‎10:27:07 AM,FwpmTransactionCommit(),0x00000005,#4319,2.3.11
‎23-‎Dec-‎18 ‏‎10:27:22 AM,FwpmEngineSetOption(),0x00000005,FWPM_ENGINE_COLLECT_NET_EVENTS,2.3.11
‎23-‎Dec-‎18 ‏‎10:27:22 AM,FwpmTransactionCommit(),0x00000005,#2123,2.3.11
‎23-‎Dec-‎18 ‏‎10:27:22 AM,FwpmTransactionCommit(),0x00000005,#4319,2.3.11
‎23-‎Dec-‎18 ‏‎10:38:01 AM,FwpmEngineSetOption(),0x00000005,FWPM_ENGINE_COLLECT_NET_EVENTS,2.3.11
‎23-‎Dec-‎18 ‏‎10:38:01 AM,FwpmTransactionCommit(),0x00000005,#2123,2.3.11
‎23-‎Dec-‎18 ‏‎10:38:01 AM,FwpmTransactionCommit(),0x00000005,#4319,2.3.11

**Comment by Polisson** [comment]
Still on beta 2.4, Win 8.1
In my case I can't to force showing up notifications.

logfile:
`"‎2019-‎02-‎27 ‏‎12:28:44","FwpmEngineSetOption()","0x00000005","FWPM_ENGINE_COLLECT_NET_EVENTS","2.4"`

**Comment by henrypp** [comment]
On latest beta (2.4.2) notifications processing speed is improved.
