### ISSUE TITLE
Skip UAC not working

### ISSUE THREAD

**Issue by fredgolightly** [henrypp/simplewall#336]
Running non-admin accounts and installing Simplewall doesn't work, so I have to run with admin rights (which is fine), but then every logon the Windows UAC prompt pops up and requires the admin password to run. Checking the 'skip uac prompt' should bypass this via task sheduler but it've tried every way I can think of and it simply does not work, it still asks for admin password via uac. How is this feature supposed to work?

**Comment by beerisgood** [comment]
I guess the skip only skip the normal "Yes / No" UAC but in your case, a password skip is necessary which isn't possible nor recommend.

If you use a non-admin (restricted) account you better disable skip UAC and create a task at task sheduler for start simplewall with adminrights which then ask for your admin password.

Or you use stuff like https://www.pcwelt.de/downloads/pcwRunAs-1215998.html (german site) which can create a task scheduler compatible way to include user passwords in encrypted file.

**Comment by nji9nji9** [comment]
I ran into the same issue.

If one is so sensitive on security issues
to take care on firewall config,
one surely won't work as admin account all day
but only if necessary.
But then, on every boot/ every log-on you have
to know/ enter the admin passwd for simplewall.

I like that program very much (especially with
my experiences with the other firewalls),
but this issue is not (good) solved in simplewall.

Using an additional 3rd party program for storing
the admin passwd IMHO is only a bad work around.

I would like to encourage the honoured devs
to keep simplewall ... well... simple and add
an option to start it before everything else
(as a service etc.).

**Comment by fredgolightly** [comment]
Any thoughts on this @henrypp ?

**Comment by Clouds123** [comment]
As @nji9nji9 suggested, splitting the user-mode part into a service (which obviously runs with Admin rights) and a GUI (which can run with limited Standard rights) is the best solution to this. The current GUI part would communicate with the service, which then communicates with the driver.

**Comment by dumpsters** [comment]
Not working for me either, I had to edit the task scheduler entry and even when editing it, I see simplewall running on task manager (from my normal user account) but it is not in the tray and I opening another simplewall.exe just opens another instance of it instead of the one already running (as admin)

**Comment by phocean** [comment]
Very nice GUI app, but not relying on a service to start indeffectively at startup is a show stopper.

It's too risky:
* it's starting too late in the process,
* a bug in the GUI could take all the app down, altogether with the filtering,
* it causes privilege issues with UAC.

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/951#issuecomment-860142760

**Comment by sh3kh4r** [comment]
Try this :)
[simplewall how to silent start.pdf](https://github.com/henrypp/simplewall/files/8086262/simplewall.how.to.silent.start.pdf)

Let me know if it works for you guys :+1:  .. @dumpsters @phocean @Clouds123 @beerisgood @henrypp

**Comment by beerisgood** [comment]
@sh3kh4r i don’t use this program since 2019 anyway nor I recommend it.

**Comment by henrypp** [comment]
@beerisgood anyway this tool is became better compared to 2019 year.

**Comment by sh3kh4r** [comment]
Hey, thanks for messaging,

What firewall do you recommend then?

⁣Regards,
- 𝔰𝔥𝔢𝔨𝔥𝔞𝔯 -​

On 17 Feb 2022, 14:44, at 14:44, beerisgood ***@***.***> wrote:
***@***.*** i don’t use this program since 2019 anyway nor I recommend it.
