### ISSUE TITLE
Show executable in blue and/or add its icon in notifications

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#344]
![image](https://user-images.githubusercontent.com/4777345/54140216-645ef680-4423-11e9-8a95-9e44f1f5bb70.png)

![screen](https://user-images.githubusercontent.com/4777345/52517790-f9ae7580-2c40-11e9-966d-f464bbf0f8b6.png)
I find that I'm really having to actively search for the name of the executable in the new notification popups. The previous layout was more compact (now there's a lot of white space and the actual information is all the way to the far right of the screen) and the name of the executable isn't colored anymore, as was the case in the old layout. Especially the latter makes it difficult to focus right away on the most important information in the dialog. Would you consider making it a link to the containing folder, so that it turns up blue and underlined again?

Following the motto "a picture says [/is worth] more than a thousand words", it might also be a good idea to include the icon of the executable in the dialog.

**Comment by pwn0r** [comment]
Meanwhile a few minor corrections, not worth opening a different issue since a screenshot is here already :)

1. _Always block_ obviously,
instead of _Always blocks_
2. It is correct to say "allow to" but "block to" is like LOL :) The correct way of saying is "to block from", and in this case it also follows by an -ing form. So it should be
_Always block this program **from accessing** the internet_

**Comment by henrypp** [comment]
@pwn0r 
my engrish is very poor, thank you!

**Comment by ltGuillaume** [comment]
![image](https://user-images.githubusercontent.com/4777345/54490834-b2f41100-48b9-11e9-9f9d-0f4626751add.png)
The buttons do not allow for two lines to show properly. This is a problem for English and I'm guessing lots of other languages, too.
