### ISSUE TITLE
Launching SW sometimes the tray icon doesn't appear

### ISSUE THREAD

**Issue by fredgolightly** [henrypp/simplewall#416]
Win 10 x64 1903 - sometimes launching simeplewall & entering admin password the icon never appears in the system tray, I have to kill the process and try again.
Load on system startup doesn't work for me - no process runs & I don't get a UAC prompt. Should it work like that?

**Comment by beerisgood** [comment]
I never say that!
Normal account is default with admin rights, but protected with UAC.

But you say that you enter a Password for admin elevation, so I guess you mean a restricted account

**Comment by fredgolightly** [comment]
Nope, that's an admin account. Check your user account type, if it's not admin it's normal, if it's admin its, well, admin. Do not run in admin, even if you're the only user. No one should run as admin.

**Comment by beerisgood** [comment]
I never say that! Read my post again.

You say that you need to enter a Password for admin elevation so i guess you mean a restricted account.

A normal Windows default account have restricted admin rights, but it protected with UAC and only then got the token to do admin stuff

**Comment by xnoreq** [comment]
@fredgolightly You don't understand how users work in Windows. If your user is member of the group "Administrators" then you don't get prompted for a valid admin account anymore by UAC. You just get a Y/N prompt if you've configured UAC to show the prompt.

If you are not member of that group but only of "Users" then you will get an UAC prompt that asks you for a valid admin account - that is user & password.

>No one should run as admin.
The whole point of developing UAC was to allow working safely as user that is in the group Administrators (so called protected admins) that run with least user privileges until they self-elevate to do administrative work.

That's why the default user on a fresh Windows installation is also in the Administrators group.

**Comment by fredgolightly** [comment]
I understand completely, I work in IT :)
As non-admin users still no one should be running as admin day to day, that's not what MS set it up for...you have to have one admin at the start else you can't set anything up...
Thanks for trying anyway!

**Comment by xnoreq** [comment]
I'm not sure you do.
It's absolutely fine to do everyday work with a user that's in the group administrators. In fact, that's the default setup and exactly what MS intended / set it up for. That's why MS developed UAC.

You may be confusing that with the pre-defined "Administrator" user. Nobody is using that except for emergency situations, and you shouldn't since it runs everything with elevated privileges. So it's not used by default.

>you have to have one admin at the start
On your private PC all you ever have to have is a single user which is an administrator... and it's totally fine.

**Comment by henrypp** [comment]
#450
