### ISSUE TITLE
Network connections monitor

### ISSUE THREAD

**Issue by Matthaiks** [henrypp/simplewall#428]
The Network tab doesn't refresh automatically, so it affects the "Have network connections" highlighting. An option to set the refresh rate or disable it would be fine.

**Comment by pwn0r** [comment]
also probably related -- if you leave simplewall windows for long enough you can notice quite a number of _waiting for connection_ entries in the network beta tab.  In that case it is impossible even to find out which app was it, as it literally named as "waiting for connection" in the UI.

**Comment by xnoreq** [comment]
@pwn0r A TCP connection in the state Time wait ("Waiting connections") is a valid connection state for TCP. It happens when the applications that made the connection didn't properly close the connection. After the process has terminated the connection is handled by the operating system.
It will eventually time out.

This has _nothing_ to do with leaving simplewall window open for a long time or refreshing.
And as the process has been terminated there's no point in associating it with a process, especially not since it's in a half-closed state anyway.

**Comment by pwn0r** [comment]
> 
> 
> @pwn0r A TCP connection in the state Time wait ("Waiting connections") is a valid connection state for TCP. It happens when the applications that made the connection didn't properly close the connection. After the process has terminated the connection is handled by the operating system.
> It will eventually time out.
> 
> This has _nothing_ to do with leaving simplewall window open for a long time or refreshing.
> And as the process has been terminated there's no point in associating it with a process, especially not since it's in a half-closed state anyway.

ok, but that should be explained properly in the UI. I'm aware about time-wait connections, however why then that would be written in the application name?
As for leaving the window long -- that is possible, as there are some refresh issues in the UI, not just network tabs propably.
