### ISSUE TITLE
Filename based rule - revisited.

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [henrypp/simplewall#463]
```
@dima-lisolyub That's a lot like #136 and cannot be easily handled, since the Windows Filtering Platform only allows full paths to a single executable.

It would require that simplewall monitors all filesystem changes in the specified folder and adds a rule as soon as a new executable pops up in the folder. It's possible, but probably not a small thing to implement.
```

```@tokariu AFAIK it's simply not possible with the sort of rules that can be created for the Windows Filtering Platform.```

```don't know if it is possible, since Windows Firewall doesn't support this.```

https://github.com/henrypp/simplewall/issues/136
https://github.com/henrypp/simplewall/issues/379
https://github.com/henrypp/simplewall/issues/307

Impossible why? If the WFP can't cope with it why not handle it inside the application? The first quote right here suggests it's possible.
Receive callback, about to  show notification popup -> perform simplewall™ pathname rule check™ -> check passes, auto mark allow or whatever the user sets.

**Comment by hesss5** [comment]
i think this can be done by driver so app should have driver
rule path with * (C:\ProgramData\Avira\Antivirus\TEMP\SELFUPDATE\********\update.exe)can be  created in netlimiter program.but on that program filter should be created manually too!
and that program wont write such wfp rule in registry i think

**Comment by henrypp** [comment]
Rules are [still strict](https://github.com/henrypp/simplewall/issues/136#issuecomment-389056619). No wildcards or masking etc.

**Comment by majkinetor** [comment]
@henrypp, I believe this is easy to achive without filtering driver as somebody suggested.

Major use case for the simplewall is to block all outgoing and incoming connections. This is set so by default with menu item _Settings -> Rules_. If this is so, simplewall popups with applicaton name and its full path when app is not recognized. This means that rather then having filter driver, in this case, one can only setup simplewall to use existing rule if app path contains known element, which should be IMO trivial to do - you basically automate user response 

It can even be done externally via some tool such as Autohotkey, clicking a button when file name is recognized. In this case:

![image](https://github.com/henrypp/simplewall/assets/85767/f662abdb-2b58-4f08-849c-2502b5078214)

AHK script can click block any time when _Network alert_ is visible with file name shown:


As of UI, one only need to add table with regex mappings such as:

|Name| Path content | Rule |
|---|---|---|
|Sharepoint| `microsoft.sharepoint.exe$` |  rule for sharepoint |
|Docker setup| `\local\temp\.+\docker\setup.exe$`| rule name for docker setup |

This would work only when above menu options (block all) are enabled, otherwise it could be grayed out. "Apps" part of the rule can be ignored.

This makes the following API limitation irrelevant:

> at's a lot like #136 and cannot be easily handled, since the Windows Filtering Platform only allows full paths to a single executable.


Since @henrypp already told us that

> No wildcards will be in simplewall, ever.

I guess AHK it is :)

**Comment by majkinetor** [comment]
Ok, here it is AHK v1.1 PoC. Add your exe names in the names section and run as Administrator. It will block that exe automatically.

```ahk
names = "microsoft.sharepoint.exe <your_exe1> <your_exe2>..."

loop, {
	IfWinExist, Network alert - simplewall
    {
		WinGetText, text
      	a := StrSplit(text, "`r`n")
       	name := Trim(a[2])
 		if (InStr(names, name)) {
            ControlClick, Button3, Network alert - simplewall
		}
	}
	Sleep 2000
}
```

**Comment by skupjoe** [comment]
Pleading for wildcard support in #1441

**Comment by majkinetor** [comment]
In the meantime, my script works great

https://github.com/henrypp/simplewall/issues/463#issuecomment-1583142497

**Comment by skupjoe** [comment]
Please support this
