### ISSUE TITLE
Blocklist menu items "Allow" actually block

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#512]
The items "Allow" in the Blocklist menu actually check all items of the category (blocking the connections), instead of unchecking them, which would allow the connections.

**Comment by henrypp** [comment]
Yes, thats right.
Blocklist menu have highest priority.

**Comment by ltGuillaume** [comment]
But doesn't it do the opposite of what it's supposed to do?

This is what I thought it should do:
- Allow: uncheck all items from that category in the blocklist tab
- Block: check all items from that category in the blocklist tab

Currently, both Allow and Block do the same.

**Comment by henrypp** [comment]
No, it's working as it named.

It has 3 states:
- Disable (you are talking about)
- Allow (it allow, obvious)
- Block (it also obvious)

Then, when you click Allow, it does not disable blocklist items - it's ALLOW them, do you understand?

**Comment by ltGuillaume** [comment]
No, I wasn't talking about disable: those actually _remove_ the entries from the Blocklist tab. That makes sense.

I was talking about Allow: since Block actually checks the items in the Blocklist tab, it would make sens if Allow _unchecks_ the items in the Blocklist tab. Currently, Allow actually _checks_ the items in the Blocklist tab, implying that they are blocked, and not allowed.

**Comment by henrypp** [comment]
> No, I wasn't talking about disable: those actually _remove_ the entries from the Blocklist tab. That makes sense.

No one was removed, it disable entries and move it to disabled group, thats what you need if you need disable.

Oh, you dont see feedback by changing icons, i think this is bug, because i have.
How do you do that allow/block?

**Comment by ltGuillaume** [comment]
No, the changed icons were there, I just simply didn't see.

I still don't understand how this works, at all.

- Disabled items: will not create any filters for those blocklist entries, right?
- When the menu item __Block__ is set: checked items have a filter to block the IP, while unchecked items are disabled (and this have no filter for the IP)
- When the menu item __Allow__ is set: checked items have a filter to explicitly allow that IP (why??) or have no filter at all? If so, what do unchecked items mean in this case?

It _would_ be cool if - when setting __Allow__ - it means that unchecked items actually have a filter to block that IP. This way, you could block _all_ items of that blocklist category, _except_ for the items that are checked (allowed).

**Comment by henrypp** [comment]
Simple things need more explanation than overloaded, i know it!

Blocklist is working as in old releases, except:

- New blocklist was grouped by it's names: **M$ Spy/Telemetry** (_spy__), **M$ Updates** (_update__), **M$ Apps** (_extra__) ([as it explained at source](https://github.com/crazy-max/WindowsSpyBlocker#telemetry-and-data-collection))

- New blocklist entries (after update, etc.) derive configuration of user selected option from menu, because it's have _high-priority_.

 - Blocklist is working like all other (system & user) rules: _checked_ is _enabled_, _unchecked_ is disabled, _green chevron_ is _permit_ access, _red chevron_ is _restrict_ access. It works like all other rules in other tabs, as i say.

- Option with high-priority are reflected on blocklist tab items. User will see all changes on tab.

- User still can disable specified items, but if high-priority option is changed by user - user choice will be reset as in option title (disable/allow/block). **It's logical!**

- ...and "Allow" implemented because of [this](https://github.com/henrypp/simplewall/issues/206#issuecomment-439830634)

ps: i think this design is better than in v2!

**Comment by ltGuillaume** [comment]
Thanks for explaining. I think it's good that there's a default setting for new entries after updates.

Do I understand correctly that the Allow mode is primarily created to **force** access to Windows Update IPs for _all_ applications, even when the applications are unchecked?

**Comment by henrypp** [comment]
> Do I understand correctly that the Allow mode is primarily created to **force** access to Windows Update IPs for _all_ applications, even when the applications are unchecked?

> Blocklist is working like all other (system & user) rules: _checked_ is _enabled_, _unchecked_ is disabled, _green chevron_ is _permit_ access, _red chevron_ is _restrict_ access. It works like all other rules in other tabs, as i say.

Yes.

**Comment by ltGuillaume** [comment]
So that way you don't have to enable network access for any process (like wuauserv, svchost etc.) to still be able to update/use the Microsoft Store? Ah that makes sense indeed.

Thanks again for explaining!

**Comment by tribals** [comment]
Let's try to make it *ALittleBitSimplier*Wall.

Built-in "rules lists" is nothing more than a list of rules. There is only one kind of rules. The rules that are created by user is "user rulse".

A rule has attributes such as protocol (icmp, ip, tcp, ...), direction (inbound, outgoing), remote and local address (with optional port - both can be ranges), and an executables.

A rules has an action: allow or block, which is indicated by "green and red chevron".

And finally, a rule has a state: enabled or disabled, which is indicated by checkbocks.

So,

A rule with action "block" in "enabled" state __blocks__ internet access for anything matching rule attributes.

Examples:

- rule with action "block" and "outgoing" direction with no protocol and addresses but with executable will block the whole internet access for application?
-- what is the point to do that if internet access is blocked by default for everything?

- rule with action "block" and "outgoing" direction with address 255.255.255.255 with no port and protocol, and no executables will block access to 255.255.255.255 through any protocol (and port)
-- "old" blacklist mode?
--- what is the point to do that ever, if everything is blocked already
---- to prevent apps with "whole" internet access to rich this particular location, possibly because is is know to be "malicious"

How to give that "whole" internet access to __trusted__ executables, then?

A rule with action "allow" in "enabled" state will allow internet access to anything matching its attributes. If it is protocol - it will be accessible for everyone. If it is address - same thing. If it is executable, and none of protocol or address is specified, app will get "whole" access to internet - but only in one direction - either inbound or outgoing.

Is that correct?

![image](https://user-images.githubusercontent.com/3613180/187050375-8f0380e8-d14c-4081-8d57-984b5e03cf06.png)

Then, where is "enable"?
