### ISSUE TITLE
simplewall.ini in wrong folder

### ISSUE THREAD

**Issue by CHEF-KOCH** [henrypp/simplewall#53]
* Extract and start SimpleWall in C:\Program Files
* It creates a simplewall.ini in C:\Program Files(x86) 

**Expected behavior**
* The simplewall.ini should be in the same place as the .exe or even better into %AppData%\SimpleWall to survive a re-installation.

**Comment by henrypp** [comment]
Seems like you are used simplewall 32-bit under 64-bit windows. Isn't?

**Comment by CHEF-KOCH** [comment]
No, I extracted it manually the binary is the correct one.

**Comment by henrypp** [comment]
`C:\Program Files` and `C:\Program Files(x86)` is UAC protected folders, and portable version is not recommended to be placed at this locations.

**Comment by CHEF-KOCH** [comment]
Auch can be disabled and it not changes the fact it places the initial file in a wrong folder.

**Comment by henrypp** [comment]
I'm tested portable version it on **clean** win10 x64 (with uac enabled) from `C:\Program Files\simplewall` and nothing is created in `C:\Program Files (x86)\simplewall`, all is writen to the same directory with `simplewall.exe`.

Maybe you are used some 3rd party appcontainer (because you are super security specialist) and forgot about it, i dont know ;)
