### ISSUE TITLE
update problems and virus problems

### ISSUE THREAD

**Issue by 0lm** [henrypp/simplewall#610]
somehow updates for your apps never work. it says "downloading" and when it hits 100%, nothing ever happens. its like its frozen. its the same with simplewall, as well as with mem reduct.
especially the language update for mem reduct from 11. january always pops up at startup since it could and can neever install it and idk why lol. i know this is not mem reduct, but how can i solve this eternal-loop problem with the language pack installation which wont be installed ever?

so i tried installing simplewall 3.1 at least manually, by downloading the exe, but windows defender blocks it and marks it as a highly risky trojan.

im on windows 10 1909 btw.

**Comment by henrypp** [comment]
this bug, you describe, is a routine bug, and it was fixed in 3.1

another question, do you trust defender?

**Comment by beerisgood** [comment]
> 
> another question, do you trust defender?

Defender is the internal protection, so it's trustworthy yes. Also best possible protection on Windows.

Anyway i scan the file with it and nothing was found. Then i upload it to Virustotal and while the last result say this file is infected now it say it's clean, after i start a rescan: https://www.virustotal.com/gui/file/1c53893dee2a9e620a1897721bdd3574dc57e58675e6ccd08b5b8e8390b3adb8/detection

**Comment by gettysburg** [comment]
@beerisgood

Best possible protection is your brain, not a closed-source software made by a company known for mining their users data.

Pathetic comment.

**Comment by gettysburg** [comment]
@beerisgood

Best possible protection is your brain, not a closed-source software made by a company known for mining their users data.

**Comment by beerisgood** [comment]
> @beerisgood
> 
> Best possible protection is your brain, not a closed-source software made by a company known for mining their users data.

I guess you don't have any valid source for that cause it's nonsense.

**Comment by gettysburg** [comment]
> 
> 
> > @beerisgood
> > Best possible protection is your brain, not a closed-source software made by a company known for mining their users data.
> 
> I guess you don't have any valid source for that cause it's nonsense.

https://answers.microsoft.com/en-us/insider/forum/all/microsoft-finally-admit-to-adware-spyware-and/83f78857-f519-4473-bb8f-e7df7ff97c68
https://www.extremetech.com/computing/247311-microsoft-finally-reveals-exactly-telemetry-windows-10-collects-pc
https://arstechnica.com/information-technology/2015/08/even-when-told-not-to-windows-10-just-cant-stop-talking-to-microsoft/
https://wccftech.com/windows-10-privacy/
https://systemoverlord.com/2015/08/16/so-is-windows-10-spying-on-you/
https://github.com/adolfintel/Windows10-Privacy

It wasn't that bad in Windows 7, but even back then they still collected way more data about users than they had to, Windows 10 is 100 times worse.

If you just made a packet dump from your router, you would see how badly a stock Windows 10 really spies on you.

The "Windows Defender" that you said is "good protection" sends your personal files back to Microsoft against your will, unless you disable it which 99% of users won't do, since the feature we are talking about is enabled by default, and if you disable it, Windows will constantly tell you to re-enable it:

https://www.askvg.com/windows-10-tip-disable-data-collection-and-telemetry-in-windows-defender/

https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Cyber-Sicherheit/SiSyPHus/Analyse_Telemetriekomponente.pdf?__blob=publicationFile&v=5

(This last one is in German, but I do suggest you translate and read it, it's from the Federal Office for Information Security in Germany, and really in-depth.)

Even if you disable all the telemetry features, data is still sent multiple times, against your will, all the time.

This claim can and has been be proven over and over with software like Wireshark, or, how ironic, even Simplewall.

There's literally thousands of non-biased sources I could cite, you are either an illiterate underage moron that has no idea how the world works or a troll - either way, not worth any serious discussion.

Have a nice day!

**Comment by beerisgood** [comment]
You need to learn that telemetry isn't about sending your personal data.

A packet dump from router wouldn't make sense as data are encrypted. You can use the Microsoft data viewer for that and then you will see that your personal data are not included.
And this is the problem nobody of the analysis guys understand. They all think that a connection most include personal data, no matter for that the connection is used - even if Microsoft list the domains in online docs.

Also defender don't send your data but a hash of the file if it is unknown in first place.

Yes. Thousand of misleading sources exist on big internet.

**Comment by gettysburg** [comment]
All information about my machine is personal, Microsoft doesn't need to see any of it (and thanks to simplewall, they won't).

Microsoft Defender can submit samples (which includes binaries) and is configured to do so by default in Windows 10 1909 unless you opt out, a hash alone won't help them to analyze possible malware (I don't think you even know how malware analysis works?), because they need the binaries in the first place. The only way to acquire binaries to analyze is to send them over to Microsoft through their SpyNet program.

This can be controlled with the Microsoft SpyNet member subscription options, which are set to "Extended" by default on the aforementioned OS, meaning defender will send in "suspicious" software, if it feels like it -  sadly, nothing is public about what is considered suspicious and scheduled to be sent in for manual analysis.

But even on Server 2019, where you can turn telemetry off almost completely, it still tries to send data that I consider personal all the time, which is completely unnecessary, most of the time using unencrypted HTTP connections to port 80, with the data easily readable as long as you reverse engineer the format they use).

Particularly, speechruntime.exe, systemsettings.exe, svchost.exe and taskhostw.exe are repeat offenders, with no easy way to disable automated data submission.

Sorry, I just like having control over what is being sent against my will - maybe you don't care about your privacy, but coming from an open source OS which I heavily customized myself, I don't trust anything closed-source by default, simply because I can't be bothered reverse-engineer the OS and kernel on every single update to find out what is being potentially sent now.

Greetings.
