### ISSUE TITLE
Anti EXE

### ISSUE THREAD

**Issue by khabib227** [henrypp/simplewall#628]
Please implement the features of Smart Object Blocker (just 1.5 mb) to Simplewall, and transform Simplewall in a perfect anti exe, anti exploit also. 

https://www.novirusthanks.org/products/smart-object-blocker/

**Comment by SeriousHoax** [comment]
Why do you want this in SimpleWall? There are other programs out there for this. It's a firewall program meant to allow or block internet connection for apps in your PC. It's no way related to any Anti EXE, it shouldn't be and I'm sure the developer has no plans for it.

**Comment by Mike-Reddick** [comment]
Have any relation? Then how have 1000 internet securities suites? If firewall, antivirus, hips, have any relation? Have others software to anti exe? Except Smart Object Blocker, please say to me at last one free option! Open Source? No one!

**Comment by SeriousHoax** [comment]
Simplewall is a firewall program and it should stay that way. The purpose of it is to be a better alternative to the built in windows firewall which is not very user friendly and customizable. There's no need to complicate things implementing features like anti exe. Personally I would stop using Simplewall if it ever takes that route but I'm pretty sure it's going to remain a firewall program only.

**Comment by graham00** [comment]
> Smart Object Blocker

Like others have said, that's completely outside the scope of what simplewall does (and how it does it). That being said, on another note...it's the first I've heard of Smart Object Blocker and while it does look neat, the fact that it's not open source would make me reluctant to run it personally.

While I do run some software that's not opensource on Windows, I try to minimize it to at least only be what I have to, and even there not run things that are not very broadly used (and with lots of time and age to them) and so at least have some degree of insight due to people having analyzed said software's behavior with firewalls and behavioral analysis tools to some extent.
