### ISSUE TITLE
Network printer does not working

### ISSUE THREAD

**Issue by helmbrandt** [henrypp/simplewall#650]
hello,

I have a network printer (IPv4), but can't print with activated simplywall, what do I need to change? Is there a service I need to whitelist?

**Comment by ObiSandwich** [comment]
Hey... I have the same problem - any chance somebody could help us out with this one as I can't use the software otherwise :(

**Comment by helmbrandt** [comment]
I tried looking for services or something to whitelist, but cant find the culprit

**Comment by A1RO** [comment]
Hey guys,

I had to enable those apps in simplewall to use my network printer:
`C:\windows\system32\dashost.exe`
`C:\windows\system32\spoolsv.exe`

From the **Apps** tab, make sure both of them are listed in the **Enabled Apps** section (those with check marks).

To do so, you could either:
- Click on checkbox to enable (if listed in the **Disabled Apps** section)
- Right-click on any existing app, **Add file...**, then click on checkbox to enable

Let us know if it worked on your side too!

**Comment by henrypp** [comment]
There is documentation which ports are used in network printer protocol.

https://www.cups.org/doc/firewalls.html

I think ports `515 (printer), 631 (ipp)` and `C:\windows\system32\spoolsv.exe` is enough to networrk printer working. I can't check this (no printer), but you can.

Let me know if it works and i can create system rule for this!

**Comment by ObiSandwich** [comment]
Thanks so much for the replies :) All networked printers seem to be working ok now, but I'll keep on testing and let you know if things change.

So after tinkering with your suggestions above, the only way I got this working was to Uninstall simplefirewall, Restart and re-install.

Then, just let the software do its thing! - opened a document for printing, pressed print and just Allowed the 2 apps simplefirewall presented;

- spoolsv.exe
- hpnetworkcommunicatorcom.exe, ‎(printer specific software)

Tested this on some of my other Windows 7 machines and the same thing happened. So happy that it's all working now :)

Thanks again for all of your help and keep up the bloody good work HENRYPP, your Firewall is awesome and after searching for a decent firewall since the birth of the internet - I've finally found one!
