### ISSUE TITLE
In windows 10 , The simplewall crashes on trying to remove access of an application

### ISSUE THREAD

**Issue by lazersharkbeam** [henrypp/simplewall#780]
In windows 10 , The simplewall crashes on trying to remove access of an application.  if an application is granted internet access and later when i try to remove that access manually from the APPS tab the application crashes.

**Comment by kekukui** [comment]
Copy the following text from Event Viewer
(**`example`**)

![Report an error](https://user-images.githubusercontent.com/20834957/94245889-ea00a500-fee8-11ea-8a6d-cd7b66f373d1.PNG)

Event ID: 1000
Source: Application Error

Faulting application name: usoclient.exe, version: 10.0.18362.628
Faulting module name: ucrtbase.dll, version: 10.0.18362.815
Exception code: 0xc0000409
Fault offset: 0x000000000006db9e

Faulting application path: C:\WINDOWS\System32\usoclient.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll

**Comment by lazersharkbeam1** [comment]
Event ID: 1002
Source: Application Hang

The program simplewall.exe version 3.2.4.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

 Process ID: 161c
 Start Time: 01d68ff9edb05718
 Termination Time: 17
 Application Path: C:\Program Files\simplewall\simplewall.exe
 Report Id: 542a9021-1458-4a30-958c-70a3680d6936
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Unknown

**_I hope this is helpful enough_**

**Comment by gettysburg** [comment]
@lazersharkbeam1 
The name of the application, module and address in / at which the exception occurred is missing which will make debugging this issue a lot harder.

If you can, please provide a dump file or attach a debugger such as x64dbg (https://x64dbg.com) to the program and as soon as it crashes, take a screenshot of the interface of x64dbg, this should provide is with enough information to fix the issue.

**Comment by gettysburg** [comment]
@lazersharkbeam1
The name of the application, module and address in / at which the exception occurred is missing which will make debugging this issue a lot harder.

If you can, please provide a dump file or attach a debugger such as x64dbg (https://x64dbg.com) to the program and as soon as it crashes, take a screenshot of the interface of x64dbg, this should provide us with enough information to fix the issue.
