### ISSUE TITLE
Rules are truncated after 255 characters

### ISSUE THREAD

**Issue by ViRb3** [henrypp/simplewall#809]
If I create a new user rule with a bunch of IPs separated by semi-columns, and the total length exceeds 255 characters, they will be truncated. I suppose the problem is here:

https://github.com/henrypp/simplewall/blob/c2c8fb12349511fb3cde7f00c3fcf8f166d58859/src/main.cpp#L5001-L5016

While I could split the rule into multiple rules, this is a pretty unexpected limitation, and it will definitely bite other people as well. Please consider allowing any length of data.

**Comment by dbmaxpayne** [comment]
Came across this as well. Thanks for researching the root cause.
Would be great if this limit was actually removed or at least a popup / text box came up when you hit the limit.
I find it weird that you simply can't continue typing in the rule editor window.

Nevertheless: Great software. Thanks a bunch :)
