### ISSUE TITLE
Firewall Profiles - set of rules

### ISSUE THREAD

**Issue by e1337** [henrypp/simplewall#866]
**Feature Request**

As a user I would like multiple profiles for different types of work I would like to perform. 
So that I can manage different rules as groups.

For example, while working I may want to have certain set of programs and tools open / blocked whereas may have a completely different profile (rules) for gaming.

**Comment by Chaython** [comment]
I asked for categories before, and the answer is just to import other profiles as wanted.
![image](https://user-images.githubusercontent.com/6486343/116506954-92118e80-a87b-11eb-885c-3847321b79ab.png)

**Comment by e1337** [comment]
Yeah , but I don't suppose you can switch between imported settings how you would be able to switch between "Profiles" easily. Or do you mean import overwrites settings? And hence can be used as a poor man's profile solution. I thought importing will just merge your current settings with what you have in profile.

**Comment by Chaython** [comment]
Ya, I guess merging imports all, you can just swap profiles by renaming profile xml
Sorry I requested it before, and it seems to be like 'why would you want to block things you trust at another time'

**Comment by arakis** [comment]
> why would you want to block things you trust at another time

I can give you a good reason: On a very low speed, payed cell phone connection, you propably want to block more traffic than if you are're using a wired internet connection in your office. This is often in my case.

Or even if it's not payed, you often you need evrey available byte for your primary application instead of less important updaters.

So, i would like profiles, too.
