### ISSUE TITLE
Please reference specific commit in .gitmodules

### ISSUE THREAD

**Issue by davidebeatrici** [henrypp/simplewall#868]
Right now this repository does not appear to be in sync with the submodules, because the following files are referenced but not existing:
```
..\routine\rapp.c
..\routine\routine.c
```

Specifying the commit in `.gitmodules` can prevent this from happening, because it causes the submodules to point to a specific "state" instead of `HEAD`.

Also, `src\editor.c` and `src\main.c` don't exist but are referenced in the project:
https://github.com/henrypp/simplewall/blob/046436fe91ca58e2eb780b2793c2a3604af6fb23/simplewall.vcxproj#L262
https://github.com/henrypp/simplewall/blob/046436fe91ca58e2eb780b2793c2a3604af6fb23/simplewall.vcxproj#L265

**Comment by henrypp** [comment]
Answer for https://github.com/henrypp/routine/commit/7a19c480388ae8b537e6a093ff3d34bdb5675fc6

yes, this is unused for new projects.
new projects used non-published version of routine, i upload new version when it is done.

by now you can use latest release from tag.

Answer for #868
>Specifying the commit in .gitmodules can prevent this from happening

i cannot specify commit in `.gitmodules` because it is out of `git` standart. I can only set [branch name](https://git-scm.com/docs/gitmodules#Documentation/gitmodules.txt-submoduleltnamegtbranch) for it, but i do nothing because of current situation with routine library.

**Comment by davidebeatrici** [comment]
Oh, I see, thank you very much for your reply!

Should I perhaps set up continuous integration for you through GitHub Actions once `master` is buildable again?

**Comment by henrypp** [comment]
Yes
