### ISSUE TITLE
Use domain names / endpoints instead of IP addresses for blocklists

### ISSUE THREAD

**Issue by ThiagoRangel7** [henrypp/simplewall#898]
IP addresses owned by Microsoft may change from time to time (or their goals - for example: an IP that today is used for updating the SO can change it's behavior next week to checking Windows licenses), and keeping lists like simplewall's blocklists to allow/block updates and telemetry is very hard and error prone.

Instead, I'd suggest the use of official Microsoft endpoints:
https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-20h2-non-enterprise-editions
https://docs.microsoft.com/en-us/windows/privacy/manage-windows-20h2-endpoints

These lists domains like `*.update.microsoft.com`, `ctldl.windowsupdate.com/*`, `*.prod.do.dsp.mp.microsoft.com` and `*.dl.delivery.mp.microsoft.com` that could be used instead of the long list of raw IP addresses for Windows Update. There are Telemetry endpoints as well, like `v10.events.data.microsoft.com` and `watson.telemetry.microsoft.com`.

Please note that some endpoints have a wildcard `*`. I think that's not supported by simplewall, at least for now.

**Comment by igitlin** [comment]
Is a good idea blocking by domain names. 
Some programs with checking updates send a many computer hardware ID
I think it would be convenient if the domain name that the program wants to connect to is also displayed. It would be easier to understand where the program is knocking.

**Comment by Chaython** [comment]
In default state, Simplewall uses https://github.com/crazy-max/WindowsSpyBlocker
It disables the services you're referring to, not only does it block the IPs, but the related apps/services are by default blocked, and many are even disabled.
So what's the point in blocking the domains?

**Comment by igitlin** [comment]
> 
> 
> In default state, Simplewall uses https://github.com/crazy-max/WindowsSpyBlocker
> It disables the services you're referring to, not only does it block the IPs, but the related apps/services are by default blocked, and many are even disabled.
> So what's the point in blocking the domains?

the meaning is very much even.
1. I would like to understand not the IP that this or that application wants to connect to, but also the domain.
1. for example there is an Adobe Premiere application with a subscription and there is a purchased NeatVideo plugin, but I want to block this plugin from accessing the Internet.
And since the plug-in does not itself, but through the host (AP) knock on its domain (whose IP is periodically changing), it is important to know the name of the domain that will then be blocked, but leave access for Adobe services.

**Comment by Chaython** [comment]
If you know the domain, you can add it to your hosts file [%SystemRoot%\system32\drivers\etc\hosts]
Remember this is just a GUI for WFP.
If you want an extensive hostfile blocking known adware/phishing etc I recommend using this https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Most plugins etc, will need a near constant ping for antipiracy reasons. Why use a plugin you do not trust? They can loopback through other means. As the plugin uses the adobe application, how would you know what traffic is related to the plugin?
To see what processes are accessing what on my computer, I use process hacker [ https://github.com/processhacker/processhacker ].

**Comment by igitlin** [comment]
adding to the host file is archaic - you could do without SimpleWall. I only want to block the plug-in activity in a specific application and not completely access the site - I still need to enter the site to download updates.
Most of my plugins do not require constant ping - they are designed to work in isolated mode, unlike Adobe programs.
> As the plugin uses the adobe application, how would you know what traffic is related to the plugin?
So for this, the domain display mode is needed - so it is immediately clear which site the program is trying to access. If Adobe wants to go to the plugin manufacturer's website, then this will be visible by the domain.
Some plugins have to be used as there is no alternative.
NeatVideo are complete assholes - they stick to buying and using from Russia. I had to buy through friends in Europe, so that would not block access. There are already many such cases of blocking without explanation of honest buyers.

**Comment by igitlin** [comment]
Now, as I understand it, the filtering mode works like this:
- Everything that is not allowed by the rules is blocked.
- SimpleWall as soon as the activity of some application appears, it shows a pop-up window in which you can block or allow access or create a rule.
- If you click allow, then all subsequent other requests for other ip will be allowed.
So it would be much more convenient for the ban or permission to work only for the specified IP in the pop-up window. So you could choose where to give the application access and where not with one button instead of the less convenient creation of rules.

**Comment by Chaython** [comment]
As you said, IPs are dynamic, so if it sent you a pop up every time any app had a new IP ping,  you would have endless notifications...
Also, most apps, a connection is only attempted once, and if the ping was unable to complete it will not try again until you restart the app and you will then lose functionality.
In security and privacy, you always have to chose between convenience or security/privacy. Simplewall is a simple GUI for allowing IP rules and apps access through the WFP. I don't know of any firewall software that is used to block domains, that's usually a separate utility, and the block is usually systemwide. 
Again if you don't trust an app, you shouldn't trust installing it on your computer.

**Comment by Chaython** [comment]
But why is it a problem? If you don't trust explorer.exe then don't allow it in the firewall, I don't know any reason to give explorer firewall access unless it's something to do with adding a network drive.

**Comment by igitlin** [comment]
it's not about trusting or not trusting completely any program. At a minimum, you need to understand where and for what this or that program wants to get access, and not mindlessly allow everything or deny everything to it. This can break functionality. For this reason, I have already said several times that it is important to know exactly where the program wants to get access and to make a decision - whether to give it access there or not.
After all, this is what SimpleWall is for, otherwise all IPs could be added to Hosts.
Naked IPs do not give knowledge of what kind of host it is - the domain name would give more information.

**Comment by Chaython** [comment]
Most firewalls don't have domain blocking, they're meant for port forwarding, blocking specific apps and IPs.
There's no functionality gained from allowing explorer.exe, if you know of one lmk.
If you want to see what something is doing, the best bet is process hacker, as it can investigate in memory, and storage access.
![image](https://user-images.githubusercontent.com/6486343/117587087-65f6d880-b0d9-11eb-905f-5bba324d8c06.png)
If you don't trust an application having access to memory[could steal passwords etc], you can right click and set it to run virtualized.
https://github.com/processhacker/processhacker
Don't run process hacker when you launch games though, destiny 2 perma banned me.

**Comment by Gennady-G** [comment]
Hi @Chaython!

> If you know the domain, you can add it to your hosts file [%SystemRoot%\system32\drivers\etc\hosts]

Thank You much for great idea to block unnecessary sites..
Interesting why do I have this site accessible, even if added to hosts file?.. oO

> 0.0.0.0 www.rbc.ru
> 0.0.0.0 rbc.ru

**Comment by henrypp** [comment]
`hosts` is not good for blocking, use dnscrypt instead!
