### ISSUE TITLE
Not getting "installed" with silent switch

### ISSUE THREAD

**Issue by OfficialEsco** [henrypp/simplewall#907]
Hey!
So i see a few people are confused after installing Simplewall with /S, which i also was after installing it via WinGet, but i also checked C:\Program Files\ and noticed simplewall actually did get "installed"(rather extracted), its just not listed in Programs and Features, no startmenu shortcut or desktop shortcut.

Is this something you can solve?
This occurs both when installed with and without administrator.
Since people install Simplewall via WinGet, scoop and Chocolatey it would be great if it installed correctly.

**Comment by Chaython** [comment]
Usually winget, choco etc are community managed, I don't think this repository mentions it being released on those services. [I don't think Henry uploaded to those services, and it was some guy who used those services....]
Does it have a portable.dat? The guy who maintains winget packages probably just put in the latest portable edition...

**Comment by OfficialEsco** [comment]
> Usually winget, choco etc are community managed, I don't think this repository mentions it being released on those services. [I don't think Henry uploaded to those services, and it was some guy who used those services....]

Pretty much any software which contains silent switches are compatible, or they could become compatible with AHK. So this statement is useless and dumb af.

> Does it have a portable.dat? The guy who maintains winget packages probably just put in the latest portable edition...

What are you on about? simplewall Repo: `You can download either the installer or portable version. For correct working, need administrator rights.` the `INSTRALLER` which in case you don't know is a `EXE` which usually support silent switches, in this case the installer is a nullsoft installer. The `PORTABLE EDITION` is a `ZIP` where it contains both the `x32` and `x64` version.

Since the `INSTALLER` is broken this is defiantly something Henry can fix.

**Comment by Chaython** [comment]
Sorry, that you're upset.
If you know so much contribute the code to fix it, instead of just calling people dumb af.
IDK why you're too lazy to install manually, and too trusting to install from a third party where there can be a malicious maintainer.
But yes, I tried silent installing, and it just moves it to program files like you said.
From the many articles I just read, silent installing is usually done by executing an msi in the package. But there's no msi in the package.

**Comment by ItzLevvie** [comment]
> Does it have a portable.dat? The guy who maintains winget packages probably just put in the latest portable edition...

My question is, how is that even possible when WinGet uses installers wherever possible (except for winpython and a few others because those publishers only make a portable version and don't create proper installers), rather than doing a portable install?

Simplewall wouldn't work in portable mode because it's not supported by WinGet :)

This statement is more targeted or related to Scoop, which highly prefers a portable install of a particular application over an installer.

So, what's the biggest issue about a portable install? You pretty much lose the ability to track your installation.

This is one of the reasons why there are lots of people complaining about this, including system admins managing hundreds of PCs. They cannot check what version of Simplewall a particular PC has installed because the ARP entry for it is completely missing?

> If you know so much contribute the code to fix it, instead of just calling people dumb af.

I agree with your point that Simplewall is open-source, but sometimes, this is generally not a good advice,

Some people out there may not be experienced in how to solve a particular issue and, therefore, will need the community's help or the developer's help to solve it.

Our Git for Windows developers at Microsoft does exactly what I have said above.

@henrypp is the one who made this application. They have the complete knowledge and experience on how their application works, how their code works, etc.

You cannot simply expect other people to match the developer's knowledge, without the developer or contributor guiding the issue author to the right place.

> IDK why you're too lazy to install manually

It isn't about being "lazy".

The whole point about a package manager is to easily allow you to manage applications on your PC. As well as to make it easy to deploy the software to over hundreds or thousands of PCs, if you're using WinGet in a commercial business.

WinGet is made by Microsoft and, therefore, this package manager is built-in to Windows. Chocolately and Scoop isn't built-in to Windows.

That would require you to capture an install.wim with Chocolately or Scoop in it and it's very tedious to update an install.wim.

As a contractor for Microsoft, Microsoft IT (MSIT), our IT department, now uses AutoPilot for Microsoft employees who use their AAD login which makes installing corporate applications much easier for our 200K employees.

With your logic, `apt` in Linux distributions shouldn't exist and people will have to download various `.deb` or `.rem` files and install the the application onto their PC. That defeats the whole purpose of package managers.

In some cases, downloading an installer over the internet may be difficult for some people.

What if someone wanted to clean install Windows 10 or 11 and that person will have to download over 200 installers over the internet to get their environment set up properly.

Why do that when you can download any application you want, as long as it's available in the package repository, by running a command in Command Prompt or Windows PowerShell or Terminal?

As you see above, it can be sophisticated. There isn't a one answer to everything. There are many pros and cons for both (or more) of these situations.

> and too trusting to install from a third party where there can be a malicious maintainer.

As a Community Moderator for WinGet myself, security concerns is the most common topic for a lot of people and I understand why a lot of people talk about it.

These security concerns are not only limited to WinGet. This applies to other package managers out there for Windows as well.

The chances of a malicious maintainer adding malware to a popular package is very slim.

Your statement doesn't take into account the sha256 of the installer(s), automated validation of the installer to see if it's considered malware or not in various anti-virus software, reputation score(s), manual review from moderators, Microsoft Defender SmartScreen, etc.

A random person simply cannot make a PR and replace it with a malicious installer. That isn't how it works for any package managers out there on Windows.

WinGet will also soon have a feature called "verified publishers". This shouldn't cause any security concerns because only the publisher can manage their packages, and contributors and moderators are likely not allowed to make any changes to their packages.

If @henrypp doesn't want other people making their application available to WinGet, then they're completely free to step up and ask to be a verified publisher once this feature has rolled out in the package repository for WinGet.

> From the many articles I just read, silent installing is usually done by executing an msi in the package.

This depends on the article you've just read.

Silent installs are not just limited to MSI installers or an MSI installer inside of an EXE installer.

There are a variety of wrappers that can wrap your application which will allow you to make a setup wizard that can allow the user to choose the location of where they want the software to install, desktop shortcuts, etc.

Each wrapper has its own silent switch available (as well as installer switches for forcing the installer not to reboot the PC once installation has finished and more) for the user to ease their application deployment.

Here are some common silent switches:

Nullsoft (NSIS): `/S`
Inno: `/VERYSILENT` or /SILENT
MSI: `/quiet` or `/passive`

> But there's no msi in the package.

This depends on what installer you're looking at.

Not all NSIS applications have to have an MSI installer inside of the EXE installer. It's not a mandatory requirement.

This issue was created because the Simplewall installer, which is based on Nullsoft (NSIS), isn't creating any registry keys when it's being silently installed with the `/S`.

This prevents anyone from actually upgrading the application in WinGet using the `winget upgrade` command.

WinGet heavily relies on the data provided from Control Panel (registry) for the management of applications, and if the installer cannot create the proper ARP entries, it cannot upgrade the application.

There's currently work being done to build a database which will allow WinGet to track applications you install in WinGet. Here's that particular pull request: https://github.com/microsoft/winget-cli/pull/1614.

FYI: This issue is completely broken by https://github.com/henrypp/builder/blob/master/setup_script.nsi#L373.
