### ISSUE TITLE
VPN split tunneling

### ISSUE THREAD

**Issue by Kali273** [henrypp/simplewall#911]
hi, when simplewall is active vpn split tunneling dont work. Can someone help me with this?

**Comment by Chaython** [comment]
I'm not sure about split tunneling, what're you using?
I personally use proton vpn, as they have many free servers, but lately they're all full....
Proton requires
ProtonVPN Service
ProtonVPN Update Service
openvpn.exe
protonvpn.exe
protonvpn.updateservice.exe
protonvpnservice.exe

So maybe just make sure your VPN's services are enabled, as you may think you only needed the exe enabled...
Otherwise knowing how you're enabling split tunneling would help me help you.

**Comment by Kali273** [comment]
Im using nord vpn, enabling split tunneling in app switch..
Have enabled-
nordvpn.exe
nordvpn-service.exe
nordvpn-service
openvpn-nordvpn.exe

**Comment by Chaython** [comment]
So what part of the split tunneling isn't working? The secure connection or the local connection? Is UPNP allowed in system rules?
Try adding a system rule to allow these ports 443 TCP and 1194 UDP as per https://nordvpn.com/blog/vpn-not-connecting/
