### ISSUE TITLE
Bug - Using Winget with simplewall results in slow downloads

### ISSUE THREAD

**Issue by brokoler** [henrypp/simplewall#988]
Hello,

I'm using Winget, the official Windows repository to install and update software packages.
Since simplewall was installed, the downloads via following Powershell commands take much longer:
- winget install <package-name>
- winget upgrade <package-name>

When simplewall is disabled, the downloads are immediately started. With simplewall enabled, it takes around 5-10 seconds until the download is started.

**Comment by Chaython** [comment]
winget might use services like BITS.

**Comment by henrypp** [comment]
Add "BITS", "DoSvc" and "UsoSvc" services to allowed list and try again.

**Comment by eggplanting** [comment]
@henrypp thank you, I whitelisted "BITS, "DoSvc" and "UsoSvc" in services tab.

It didn't help though, installing and updating apps via Winget ist still really slow when simplewall is enabled.
Do you have any other idea which services to whitelist? I will try to troubleshoot this further.

Thanks!

**Comment by henrypp** [comment]
@eggplanting

> Do you have any other idea which services to whitelist? I will try to troubleshoot this further.

"App Installer" (uwp app) and "appinstallercli.exe" (win32 app), also may be helpful disable Blocklist update section.

**Comment by eggplanting** [comment]
App Installer UWP app is missing for me, appinstallercli.exe got all permissions.
What exactly do you mean with "disable Blocklist update section"?

I enabled all Microsoft Updater rules in the blocklist globally, which for example allows me to search for Windows Updates.
Also enabled all other Blocklist rules globally for testing, this didn't help to solve the problem.

**Comment by henrypp** [comment]
> What exactly do you mean with "disable Blocklist update section"?

Disable or Allow blocklist update section, it is not required, just for testing.

**Comment by Chaython** [comment]
![image](https://user-images.githubusercontent.com/6486343/130368562-b2f4b145-83d9-46bf-bb57-adc9a27bfa92.png)
![image](https://user-images.githubusercontent.com/6486343/130368578-92ddb04b-8961-44f8-8088-140422736f2b.png)
![image](https://user-images.githubusercontent.com/6486343/130368593-7df7444c-f30f-477a-aa26-f733ed610b39.png)
Anyways, ask on winget https://github.com/microsoft/winget-cli all dependencies, but if all MSFT servers are set to allow, it doesn't make sense that it would only be slower.
Also winget is bad, because of these dependencies, because lack of moderation of repos... If you want a cli package manager try choclatey or the many others pre-dating microcrap.
The download speeds via msft store are very slow for me or any of my friends, who don't use simplewall. [I get 600mbps with steam, only <150mbps with msft store and often as low as 1mb/s] my friend has fiber/gigabit, and was only getting 24mbps via Xbox store.
Unlike most other major companies, MSFT doesn't seem to have local cacheing servers for its appstores, like steam just downloads from my ISP. MSFT does their own hosting rather than good CDNs.

**Comment by vedantmgoyal2009** [comment]
> winget might use services like BITS and DO.

Sometimes, users can set `wininet` as the default service so whitelisting that would also make sense.
